from pathlib import Path

svc = Path('server/cpaOrganization/verifiedCustomerContinuationService.ts')
s = svc.read_text()

# Version the continuation logic so terminal states from an older implementation
# are re-evaluated on the same completed job without deleting evidence or creating a new intake.
anchor = "export type VerifiedContinuationStatus =\n"
if anchor not in s:
    raise SystemExit('status anchor missing')
s = s.replace(anchor, "export const VERIFIED_CONTINUATION_LOGIC_VERSION = 'v2-balance-period-aliases';\n\n" + anchor, 1)

old = """  continuationId: string;\n  jobId: string;"""
new = """  continuationId: string;\n  logicVersion?: string;\n  previousStatus?: VerifiedContinuationStatus;\n  jobId: string;"""
if old not in s:
    raise SystemExit('state interface anchor missing')
s = s.replace(old, new, 1)

# Prefer the fact's actual reporting period. periodStart/periodEnd may describe
# the extraction statement context and can be 2024 even for a 2023 comparative row.
old = """function factYear(f: any): number | null {\n  const text = `${f?.reportingPeriod || ''} ${f?.periodEnd || ''} ${f?.periodStart || ''}`;\n  const years = [...text.matchAll(/\\b(20\\d{2})\\b/g)].map(m => Number(m[1]));\n  return years.length ? Math.max(...years) : null;\n}"""
new = """function yearsIn(value: any): number[] {\n  return [...String(value || '').matchAll(/\\b(20\\d{2})\\b/g)].map(m => Number(m[1]));\n}\n\nfunction factYear(f: any): number | null {\n  const reportingYears = yearsIn(f?.reportingPeriod);\n  if (reportingYears.length) return Math.max(...reportingYears);\n  const fallbackYears = [...yearsIn(f?.periodEnd), ...yearsIn(f?.periodStart)];\n  return fallbackYears.length ? Math.max(...fallbackYears) : null;\n}"""
if old not in s:
    raise SystemExit('factYear anchor missing')
s = s.replace(old, new, 1)

# Use canonical aliases actually emitted by SEC/XBRL extraction. The equity key
# must represent total equity including NCI when available, because that is the
# amount that participates in Assets = Liabilities + Equity.
old = """export function deriveCurrentBalance(facts: any[], fiscalYear: string): { assets: number; liabilities: number; equity: number; variance: number } | null {\n  const assets = uniqueMetricValue(facts, ['totalAssets', 'total_assets'], fiscalYear);\n  const liabilities = uniqueMetricValue(facts, ['totalLiabilities', 'total_liabilities'], fiscalYear);\n  const equity = uniqueMetricValue(facts, ['totalEquity', 'total_equity'], fiscalYear);\n  if (assets === null || liabilities === null || equity === null) return null;\n  return { assets, liabilities, equity, variance: Math.abs(assets - (liabilities + equity)) };\n}"""
new = """export function deriveCurrentBalance(facts: any[], fiscalYear: string): { assets: number; liabilities: number; equity: number; variance: number } | null {\n  const assets = uniqueMetricValue(facts, ['assets', 'totalAssets', 'total_assets'], fiscalYear);\n  const liabilities = uniqueMetricValue(facts, ['liabilities', 'totalLiabilities', 'total_liabilities'], fiscalYear);\n  const equity = uniqueMetricValue(facts, [\n    'stockholdersEquityIncludingPortionAttributableToNoncontrollingInterest',\n    'totalEquity',\n    'total_equity',\n    'equityIncludingNoncontrollingInterest'\n  ], fiscalYear);\n  if (assets === null || liabilities === null || equity === null) return null;\n  return { assets, liabilities, equity, variance: Math.abs(assets - (liabilities + equity)) };\n}"""
if old not in s:
    raise SystemExit('deriveCurrentBalance anchor missing')
s = s.replace(old, new, 1)

# Same-attempt terminal suppression is valid only for the current continuation logic.
old = """    if (!state) return false;\n    if (state.jobAttempt !== Number(job?.attemptCount || 0) || state.sourceSha256 !== job?.documentHash) return false;\n    return ["""
new = """    if (!state) return false;\n    if (state.logicVersion !== VERIFIED_CONTINUATION_LOGIC_VERSION) return false;\n    if (state.jobAttempt !== Number(job?.attemptCount || 0) || state.sourceSha256 !== job?.documentHash) return false;\n    return ["""
if old not in s:
    raise SystemExit('terminal version anchor missing')
s = s.replace(old, new, 1)

old = """    const base: VerifiedContinuationState = {\n      continuationId: this.continuationId(job.id),\n      jobId: job.id,"""
new = """    const base: VerifiedContinuationState = {\n      continuationId: this.continuationId(job.id),\n      logicVersion: VERIFIED_CONTINUATION_LOGIC_VERSION,\n      previousStatus: prior?.status,\n      jobId: job.id,"""
if old not in s:
    raise SystemExit('base version anchor missing')
s = s.replace(old, new, 1)

# Never reuse specialist output generated by an older continuation logic version.
old = """      if (prior?.specialistSummary && prior.jobAttempt === base.jobAttempt && prior.sourceSha256 === base.sourceSha256) {"""
new = """      if (prior?.logicVersion === VERIFIED_CONTINUATION_LOGIC_VERSION && prior?.specialistSummary && prior.jobAttempt === base.jobAttempt && prior.sourceSha256 === base.sourceSha256) {"""
if old not in s:
    raise SystemExit('specialist reuse version anchor missing')
s = s.replace(old, new, 1)

svc.write_text(s)

# Expand the targeted regression to reproduce the real Pfizer comparison-period bug
# and real canonical metric aliases.
test = Path('server/tests/company1VerifiedContinuation.test.ts')
t = test.read_text()
t = t.replace(
    'import { isProofCompleteFact, selectProofCompleteFacts, deriveFiscalYear, deriveCurrentBalance, buildVerifiedFactDigest } from "../cpaOrganization/verifiedCustomerContinuationService.js";',
    'import { isProofCompleteFact, selectProofCompleteFacts, deriveFiscalYear, deriveCurrentBalance, buildVerifiedFactDigest, VERIFIED_CONTINUATION_LOGIC_VERSION } from "../cpaOrganization/verifiedCustomerContinuationService.js";',
    1
)
old = """const bal = deriveCurrentBalance(proof, \"2024\");\nassert(!!bal && bal.variance === 0, \"verified Pfizer-class balance sheet must reconcile before continuation\");\nassert(buildVerifiedFactDigest(proof).every(f => f.verificationStatus === \"VERIFIED\" && f.evidenceStatus === \"CONFIRMED\"), \"fact digest must retain proof lineage\");"""
new = """const bal = deriveCurrentBalance(proof, \"2024\");\nassert(!!bal && bal.variance === 0, \"verified Pfizer-class balance sheet must reconcile before continuation\");\n\n// Reproduce the physical Pfizer bug: comparative 2023 rows inherited 2024 statement\n// context dates, while reportingPeriod correctly identifies the comparative date.\nconst pfizerLike: any[] = [\n  { ...base, id: 'a24', canonicalMetric: 'assets', reportingPeriod: '2024-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 213396000000 },\n  { ...base, id: 'a23', canonicalMetric: 'assets', reportingPeriod: '2023-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 226501000000 },\n  { ...base, id: 'l24', canonicalMetric: 'liabilities', reportingPeriod: '2024-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 124899000000 },\n  { ...base, id: 'l23', canonicalMetric: 'liabilities', reportingPeriod: '2023-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 137213000000 },\n  { ...base, id: 'e24', canonicalMetric: 'stockholdersEquityIncludingPortionAttributableToNoncontrollingInterest', reportingPeriod: '2024-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 88497000000 },\n  { ...base, id: 'e23', canonicalMetric: 'stockholdersEquityIncludingPortionAttributableToNoncontrollingInterest', reportingPeriod: '2023-12-31', periodStart: '2024-01-01', periodEnd: '2024-12-31', normalizedValue: 89288000000 }\n];\nassert(deriveFiscalYear(pfizerLike) === '2024', 'current fiscal year must remain 2024');\nconst pfizerBalance = deriveCurrentBalance(pfizerLike, '2024');\nassert(!!pfizerBalance, 'Pfizer canonical SEC aliases must produce a current-period balance');\nassert(pfizerBalance!.assets === 213396000000 && pfizerBalance!.liabilities === 124899000000 && pfizerBalance!.equity === 88497000000, 'comparative 2023 rows must not contaminate the 2024 identity');\nassert(pfizerBalance!.variance === 0, 'physical Pfizer 2024 balance sheet must reconcile exactly');\nassert(VERIFIED_CONTINUATION_LOGIC_VERSION === 'v2-balance-period-aliases', 'continuation logic must be versioned so prior terminal evaluations can be safely reconsidered');\nassert(buildVerifiedFactDigest(proof).every(f => f.verificationStatus === \"VERIFIED\" && f.evidenceStatus === \"CONFIRMED\"), \"fact digest must retain proof lineage\");"""
if old not in t:
    raise SystemExit('targeted test anchor missing')
t = t.replace(old, new, 1)
# Static guard for the idempotency/version boundary.
t = t.replace(
    'assert(server.includes("continueCompletedHybridJob(job, db)"), "completed hybrid jobs must flow into verified continuation");',
    'assert(server.includes("continueCompletedHybridJob(job, db)"), "completed hybrid jobs must flow into verified continuation");\nconst continuationSource = fs.readFileSync("server/cpaOrganization/verifiedCustomerContinuationService.ts", "utf8");\nassert(continuationSource.includes("state.logicVersion !== VERIFIED_CONTINUATION_LOGIC_VERSION"), "terminal continuation state must be version-scoped");',
    1
)
test.write_text(t)
