import express, { type Request, type Response, type NextFunction } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { IdentityStore, admin, internal, random, digest, roles, safeUser, type User } from './identityStore.js';
import { page, escape as e, input, csrf, table, mark, marketing, demoThanks, notFound } from './portalPages.js';
import { readOwnerEngagements } from '../cpaOrganization/ownerEngagementReadModel.js';
import { supportStore } from '../support/supportStore.js';
import { universityStore } from '../university/universityStore.js';
import { rawInputHermesContinuationService } from '../cpaOrganization/rawInputHermesContinuation.js';
const COOKIE='__Host-eve_session', PRE='__Host-eve_login_csrf', CSRF='__Host-eve_csrf';
const publicLeadAttempts=new Map<string,{count:number;resetAt:number}>();
const isPublicHost=(hostname:string)=>['evesbookkeeping.com','www.evesbookkeeping.com',...(process.env.EVE_PUBLIC_PREVIEW_HOSTS||'').split(',').map(value=>value.trim().toLowerCase()).filter(Boolean)].includes(hostname.toLowerCase());
export const identityStore=new IdentityStore();
const cookie=(req:Request,name:string)=>{try{return decodeURIComponent((req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'');}catch{return '';}};
const setCookie=(res:Response,name:string,value:string,age=43200,httpOnly=true)=>res.append('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; Secure; ${httpOnly?'HttpOnly; ':''}SameSite=Strict; Max-Age=${age}`);
const safeOrigin=(req:Request)=>{if(req.get('sec-fetch-site')==='cross-site')return false;const origin=req.get('origin');if(!origin)return false;try{return new URL(origin).origin===`https://${req.get('host')}`;}catch{return false;}};
const fail=(res:Response,status:number,message:string)=>res.status(status).type('html').send(page('Access',`<section class="card auth"><h1>Unable to continue</h1><p class="error">${e(message)}</p><a href="/login">Sign in</a></section>`));
const summary=(r:any)=>({workspaceId:r.workspaceId,engagementId:r.engagementId,clientName:r.clientName,status:r.status,period:r.period,documentsCount:r.documentsCount,canonicalFactsCount:r.canonicalFactsCount});
function customerData(u:User,store:IdentityStore){const tenant=store.read().tenants.find(t=>t.id===u.tenantId);return tenant?readOwnerEngagements().filter(r=>tenant.workspaceIds.includes(r.workspaceId)):[];}
function customerProjection(r:any){return {...summary(r),periods:r.periods,numericVariance:r.numericVariance,documents:r.documents.map((d:any)=>({id:d.id,filename:d.filename,sha256:d.sha256,mimeType:d.mimeType})),facts:r.facts.filter((f:any)=>String(f.status||'').toUpperCase()==='APPROVED'&&['VERIFIED','EVIDENCE_CONFIRMED'].includes(String(f.verificationStatus||f.verification_status||'').toUpperCase())&&String(f.evidenceStatus||f.evidence_status||'').toUpperCase()==='CONFIRMED').map((f:any)=>Object.fromEntries(['id','label','metric','value','period','reportingPeriod','currency','unit','scale','sourceText','documentId'].map(k=>[k,f[k]]))),findings:r.findings.filter((f:any)=>f.customerVisible===true).map((f:any)=>({id:f.id,title:f.title,message:f.message,status:f.status})),reports:r.reports.map((p:any)=>({reportId:p.reportId,version:p.version,status:p.status,title:p.title,formats:Object.keys(p.formats)}))};}
const ownerSections=['overview','customers','support','engagements','documents','exceptions','university','academy','agents','reports','users','system','audit'];
const controlLink=(href:string,label:string)=>`<a class="control-link" href="${e(href)}">${e(label)}</a>`;
const controlTable=(headers:string[],rows:string[][])=>`<div class="scroll"><table class="responsive-table"><thead><tr>${headers.map(value=>`<th>${e(value)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((value,index)=>`<td data-label="${e(headers[index]||'')}">${value}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No records available.</td></tr>`}</tbody></table></div>`;
const previewDate=(value:string|null|undefined)=>value?e(new Date(value).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'})): 'Not recorded';
const caseBadge=(value:string)=>`<span class="status-badge">${e(value.replaceAll('_',' '))}</span>`;
function universityDashboard(){
 const snapshot=universityStore.snapshot(),overview=snapshot.overview;
 const metric=(label:string,value:any)=>`<section class="card"><p>${e(label)}</p><div class="stat">${e(value)}</div></section>`;
 const simple=(title:string,headers:string[],rows:any[][])=>`<section class="card"><h2>${e(title)}</h2>${table(headers,rows.map(row=>row.map(value=>String(value??'—'))))}</section>`;
 return `<div class="grid">${[
  ['Active examinations',overview.active],['Grading',overview.grading],['Remediation',overview.remediation],['Queue depth',overview.queueDepth],
  ['Physical workers',overview.workersActive],['Regression passed',overview.regressionHealthy],['Owner requests',overview.ownerRequestsOpen],['Total examinations',overview.examinations]
 ].map(([label,value])=>metric(String(label),value)).join('')}</div>
 <section class="card"><h2>University Overview</h2><p>Raw document → understanding → evidence → canonical accounting → posting/workpapers → reconciliation or clarification → books → deliverable → reverse lineage → sealed Minerva grade.</p><p>Only physical execution evidence changes a capability from UNTESTED. Academy success does not grant production autonomy or professional approval.</p><a class="button" href="/workspace?view=eve-university">Open interactive University evidence</a></section>
 ${simple('Live Examinations',['Examination','Name','Stage','Result'],snapshot.liveExaminations.map((row:any)=>[row.examinationId,row.name,row.stage,row.result]))}
 ${simple('Synthetic Customers',['Tenant','Workspace','Classification','Result'],snapshot.syntheticCustomers.map((row:any)=>[row.tenantId,row.workspaceId,row.classification,row.result]))}
 ${simple('Raw Input Lab',['Examination','Source','Documents','Stage','Result'],snapshot.rawInputLab.map((row:any)=>[row.examinationId,row.sourceType,row.documentCount,row.stage,row.result]))}
 ${simple('Capability Matrix',['Capability','Name','Status','Physical executions'],snapshot.capabilityMatrix.map((row:any)=>[row.capabilityId,row.name,row.result,row.physicalExecutions]))}
 ${simple('Failures & Remediation',['Failure','Examination','Stage','Status'],snapshot.failuresRemediation.map((row:any)=>[row.failureId,row.examinationId,row.stage,row.status]))}
 ${simple('Regression',['Regression','Examination','Result','Hidden holdout'],snapshot.regression.map((row:any)=>[row.regressionId,row.examinationId,row.status,row.hiddenHoldoutId]))}
 ${simple('Minerva',['Examination','Stage','Result','Updated'],snapshot.minerva.map((row:any)=>[row.examinationId,row.stage,row.result,row.updatedAt]))}
 ${simple('Workforce',['Worker','Examination','Stage','Status','Started'],snapshot.workforce.map((row:any)=>[row.workerId,row.examinationId,row.stage,row.status,row.startedAt]))}
 ${simple('Hermes',['Metric','Recorded value'],[['Queue depth',snapshot.hermes.queueDepth],['Active workers',snapshot.hermes.activeWorkers],['Physical executions',snapshot.hermes.physicalExecutions],['Idle reason',snapshot.hermes.idleReason]])}
 ${simple('Learning / Darwin',['Failure','Root cause','Capability gap','Status'],snapshot.learningDarwin.map((row:any)=>[row.failureId,row.rootCause,row.capabilityGap,row.status]))}
 ${simple('Curriculum',['Retained cases','Sealed holdouts'],[[snapshot.curriculum.retainedCases,snapshot.curriculum.sealedHoldouts]])}
 ${simple('Owner Requests',['Request','Agent','Capability','Priority','Status'],snapshot.ownerRequests.map((row:any)=>[row.requestId,row.requestingAgent,row.proposedCapability,row.priority,row.status]))}
 ${rawAccountingPanels(rawInputHermesContinuationService.getAllContinuations(),'Raw Accounting Case State')}`;
}
function rawAccountingPanels(continuations:any[],heading='Raw Accounting Continuation'){
 if(!continuations.length)return `<section class="card"><h2>${e(heading)}</h2><p>No tenant-scoped raw accounting continuation is recorded.</p></section>`;
 return continuations.map(row=>{
  const stage=(name:string)=>row.executions.find((execution:any)=>execution.stage===name&&execution.status==='COMPLETED')?.resultData||{};
  const canonical=stage('CANONICALIZATION').canonicalTransactions||[],classified=stage('ACCOUNTING_CLASSIFICATION').classifiedTransactions||[];
  const workpaper=stage('POSTING_WORKPAPER').workpaper||null,deliverable=stage('REPORT_DELIVERABLE'),lineage=stage('LINEAGE_VERIFICATION'),minerva=stage('MINERVA_GRADING');
  const formats=Object.entries(deliverable.formats||{}).map(([format,item]:any)=>[String(format).toUpperCase(),item.sha256,item.sizeBytes]);
  const journalRows=classified.flatMap((transaction:any)=>{const journal=transaction.journal||{};return [...(journal.debits||[]).map((line:any)=>[journal.journalId,'Debit',line.accountCode,line.accountName,line.amount,journal.currency,journal.status]),...(journal.credits||[]).map((line:any)=>[journal.journalId,'Credit',line.accountCode,line.accountName,line.amount,journal.currency,journal.status])];});
  return `<section class="card raw-accounting-case"><p class="eyebrow">Tenant-scoped raw-input case</p><h2>${e(heading)}</h2>
   ${table(['Continuation','Document kind','State','Latest stage','Latest outcome'],[[row.continuationId,row.documentKind,row.status,row.executions.at(-1)?.stage||'Queued',row.executions.filter((execution:any)=>execution.outcomeCode).at(-1)?.outcomeCode||'Pending']])}
   <h3>Processing and accounting stages</h3>${table(['Stage','Worker','Status','Outcome','Receipt'],row.executions.map((execution:any)=>[execution.stage,execution.workerId,execution.status,execution.outcomeCode||'Pending',execution.receiptHash||'Not recorded']))}
   <h3>Transaction facts</h3>${table(['Transaction','Counterparty','Date','Currency','Amount','Payment','Category','Evidence'],canonical.map((transaction:any)=>[transaction.canonicalTransactionId,transaction.counterparty||'Not supported',transaction.date||'Not supported',transaction.currency||'Not supported',transaction.amount,transaction.paymentMethod||'Not supported',transaction.accountingCategory||'Not supported',transaction.evidenceStatus||'Not recorded']))}
   <h3>Evidence and provenance</h3>${table(['Fact','Document','Source SHA-256','Source block / coordinate','Literal'],row.facts.map((fact:any)=>[fact.id,fact.documentId||row.documentId,fact.sourceSha256||'Not recorded',fact.sourceCoordinate?.coordinateId||fact.sourceCoordinate?.sourceBlockId||fact.sourceBlockId||'Not recorded',fact.sourceCoordinate?.rawLiteral||fact.sourceText||'Not recorded']))}
   <h3>Workpaper / books</h3>${table(['Workpaper','State','Posting','Balanced','Journals','Professional approval'],workpaper?[[workpaper.workpaperId,workpaper.status,workpaper.postingState,workpaper.control?.balanced?'YES':'NO',workpaper.control?.journalCount,workpaper.professionalApproval]]:[])}
   ${table(['Journal','Side','Account','Account name','Amount','Currency','State'],journalRows)}
   <h3>Four-format deliverable</h3>${table(['Report','Version','State','Canonical fact hash'],deliverable.reportId?[[deliverable.reportId,deliverable.version,deliverable.status,deliverable.canonicalFactHash]]:[])}${table(['Format','SHA-256','Bytes'],formats)}
   <h3>Reverse lineage</h3>${table(['Report','Workpaper','Journal','Canonical transaction','Fact','Document','Source SHA-256'],(lineage.reverseLineage||[]).map((item:any)=>[item.reportId,item.workpaperId,item.journalId,item.canonicalTransactionId,item.factId,item.documentId,item.sourceSha256]))}
   <h3>Independent Minerva</h3>${table(['Result','Evaluation','Dimensions passed'],minerva.minervaResult?[[minerva.minervaResult,minerva.report?.evaluationId||'Recorded',`${minerva.report?.passedDimensionCount||0}/5`]]:[])}
  </section>`;
 }).join('');
}
function navigation(u:User,token:string){return `${internal(u)?'<a href="/owner">Control center</a><a href="/workspace">Accounting workspace</a>':'<a href="/portal">My organization</a><a href="/portal/support">Help &amp; support</a>'}<a href="/account">My account</a><form class="inline" method="post" action="/auth/logout">${csrf(token)}<button data-eve-action-id="auth.logout">Log out</button></form>`;}
export function createAccessPortal(store=identityStore){
 const router=express.Router();
 router.use((req,res,next)=>req.path==='/api/portal/intake'?next():express.json({limit:'16kb'})(req,res,next));
 router.use((req,res,next)=>{const publicHost=isPublicHost(req.hostname||'');if(['/login','/account','/owner','/portal','/public','/password-help','/auth'].some(p=>req.path===p||req.path.startsWith(p+'/')))res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");else if(publicHost)res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self'; script-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'");res.set({'Cache-Control':publicHost?'public, max-age=300':'private, no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':publicHost?'strict-origin-when-cross-origin':'same-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'});if(req.path.startsWith('/auth/')||req.path==='/request-demo'){express.urlencoded({extended:false,limit:'16kb'})(req,res,err=>err?fail(res,400,'Invalid request.'):next());}else next();});
 router.use((req,res,next)=>{
  try {
   if(req.method==='GET'&&req.path==='/brand/eve.svg'){res.type('image/svg+xml').send(mark);return;}
   const hostname=(req.hostname||'').toLowerCase();
   const publicHost=isPublicHost(hostname);
   if(hostname==='www.evesbookkeeping.com'){res.redirect(308,`https://evesbookkeeping.com${req.originalUrl||'/'}`);return;}
   if(publicHost&&req.method==='GET'&&req.path.startsWith('/brand/product/')){const file=path.basename(req.path);if(!/^eve-product-[a-z0-9-]+\.jpg$/i.test(file)){res.sendStatus(404);return;}const target=path.join(process.cwd(),'dist','brand','product',file);if(fs.existsSync(target)){res.sendFile(target);return;}res.sendStatus(404);return;}
   if(publicHost&&req.method==='GET'&&req.path.startsWith('/brand/')){const file=path.basename(req.path);if(!/^[a-z0-9._-]+$/i.test(file)){res.sendStatus(404);return;}const target=path.join(process.cwd(),'dist','brand',file);if(fs.existsSync(target)){res.sendFile(target);return;}const og=file.match(/^og-([a-z0-9-]+)\.svg$/i);if(og){const label=og[1].split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');res.type('image/svg+xml').send(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><defs><linearGradient id="g"><stop stop-color="#0B2D4D"/><stop offset="1" stop-color="#123F63"/></linearGradient></defs><rect width="1200" height="630" fill="url(#g)"/><circle cx="1040" cy="80" r="260" fill="#14B8A6" opacity=".18"/><path d="M0 540L300 350 480 470 760 260 1200 520V630H0Z" fill="#fff" opacity=".09"/><circle cx="130" cy="132" r="56" fill="#2563EB"/><text x="130" y="153" text-anchor="middle" font-family="Georgia" font-size="64" font-weight="700" fill="white">E</text><text x="220" y="145" font-family="Arial" font-size="38" font-weight="700" fill="white">Eve's Bookkeeping</text><text x="100" y="330" font-family="Georgia" font-size="72" font-weight="700" fill="white">${e(label==='Home'?'Bookkeeping Intelligence':label)}</text><text x="100" y="405" font-family="Arial" font-size="30" fill="#CDE1EE">Clear Numbers. Brighter Tomorrows.</text></svg>`);return;}res.sendStatus(404);return;}
   if(publicHost&&req.method==='GET'&&req.path==='/robots.txt'){res.type('text/plain').send('User-agent: *\nAllow: /\nDisallow: /login\nDisallow: /portal\nDisallow: /owner\nDisallow: /workspace\nDisallow: /api/\nSitemap: https://evesbookkeeping.com/sitemap.xml\n');return;}
   if(publicHost&&req.method==='GET'&&req.path==='/sitemap.xml'){const urls=['','product','businesses','cpa-firms','pricing','how-it-works','security','quality','about','contact','privacy','terms','accessibility'];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>https://evesbookkeeping.com/${x}</loc></url>`).join('')}</urlset>`);return;}
   if(publicHost&&req.method==='POST'&&req.path==='/request-demo'){
    const key=req.socket.remoteAddress||'unknown',now=Date.now(),attempt=publicLeadAttempts.get(key);if(attempt&&attempt.resetAt>now&&attempt.count>=5){res.status(429).type('html').send(page('Request a demo','<section class="card auth"><h1>Please try again later</h1><p class="error">Too many demo requests were submitted from this connection.</p><a href="/contact">Return to contact</a></section>'));return;}if(!attempt||attempt.resetAt<=now)publicLeadAttempts.set(key,{count:1,resetAt:now+60*60*1000});else attempt.count+=1;
    const name=String(req.body?.name||'').trim(),email=String(req.body?.email||'').trim(),organization=String(req.body?.organization||'').trim(),audience=String(req.body?.audience||'').trim(),message=String(req.body?.message||'').trim();
    if(req.body?.website){res.type('html').send(demoThanks());return;}
    if(!name||name.length>120||!/^\S+@\S+\.\S+$/.test(email)||email.length>254||!organization||organization.length>160||!audience||!message||message.length>2000||req.body?.consent!=='yes'){res.status(400).type('html').send(page('Request a demo','<section class="card auth"><h1>Check your request</h1><p class="error">Complete every required field with a valid work email.</p><a href="/contact">Return to the form</a></section>'));return;}
    const root=process.env.EVE_PUBLIC_LEADS_DIR||path.join(process.cwd(),'storage','public-leads');fs.mkdirSync(root,{recursive:true});const day=new Date().toISOString().slice(0,10),file=path.join(root,`${day}.jsonl`);fs.appendFileSync(file,JSON.stringify({id:random(),receivedAt:new Date().toISOString(),name,email:email.toLowerCase(),organization,audience,message})+'\n',{mode:0o600});res.status(201).type('html').send(demoThanks());return;
   }
   if(publicHost&&req.method==='GET'){const slug=req.path==='/'?'home':req.path.slice(1);const html=marketing(slug,req.originalUrl||'');if(html){res.type('html').send(html);return;}res.status(404).type('html').send(notFound());return;}
   if(req.method==='GET'&&req.path==='/'){
    if(hostname==='owner.evesbookkeeping.com'){res.redirect('/owner');return;}
    if(hostname==='app.evesbookkeeping.com'){res.redirect('/portal');return;}
   }
   if(req.method==='GET'&&(req.path==='/public'||req.path.startsWith('/public/'))){const html=marketing(req.path.slice(8)||'home');if(!html){res.sendStatus(404);return;}res.type('html').send(html);return;}
   if(req.method==='GET'&&req.path==='/login'){const token=random();setCookie(res,PRE,token,1800);res.type('html').send(page('Sign in',`<section class="card auth"><div class="eyebrow">Secure workspace</div><h1>Welcome to Eve</h1><p>Sign in with your account. New invitations require a permanent password before opening your workspace.</p><form method="post" action="/auth/login">${csrf(token)}${input('email','Email','email','required autocomplete="username" maxlength="254"')}${input('password','Password','password','required autocomplete="current-password" maxlength="256"')}<button data-eve-action-id="auth.login">Sign in</button></form><a href="/password-help">Forgot your password?</a><p><a href="/operator-login">Temporary development access</a></p></section>`));return;}
   if(req.method==='GET'&&req.path==='/password-help'){res.type('html').send(page('Account recovery',`<section class="card auth"><h1>Recover your account</h1><p>Ask your platform administrator for a new one-time setup password. Resetting your account revokes existing sessions. Your permanent password is never disclosed.</p><p>Owner recovery is available through the protected deployment administration command. Automatic email recovery is not enabled until a delivery provider is configured.</p><a href="/login">Back to sign in</a></section>`));return;}
   if(req.method==='POST'&&req.path==='/auth/login'){
    if(!safeOrigin(req)||!cookie(req,PRE)||digest(String(req.body.csrf||''))!==digest(cookie(req,PRE))){fail(res,403,'Sign-in request expired. Reload the sign-in page.');return;}
    const result=store.login(String(req.body.email||''),String(req.body.password||''),req.socket.remoteAddress||'unknown');if(!result){fail(res,401,'Email or password was not accepted.');return;}setCookie(res,COOKIE,result.token,result.session.restricted?1800:43200);setCookie(res,CSRF,result.session.csrf,result.session.restricted?1800:43200,false);setCookie(res,PRE,'',0);res.redirect(303,result.session.restricted?'/account/password':internal(result.user)?'/owner':'/portal');return;
   }
   const token=cookie(req,COOKIE),ctx=store.session(token);
   if(!ctx){if(req.path.startsWith('/auth/')||['/owner','/portal','/account'].some(p=>req.path===p||req.path.startsWith(p+'/'))||req.path.startsWith('/api/portal/')||req.path==='/api/access/session'){if(req.path.startsWith('/api/'))res.status(401).json({error:'SIGN_IN_REQUIRED'});else res.redirect('/login');return;}next();return;}
   const {user,session}=ctx;(req as any).eveIdentity=ctx;
   if(!['GET','HEAD','OPTIONS'].includes(req.method)){
    const csrfValue=req.get('x-eve-csrf')||req.body?.csrf||(req.path==='/api/portal/intake'&&req.is('multipart/form-data')?cookie(req,CSRF):'');
    if(!safeOrigin(req)||digest(String(csrfValue||''))!==digest(session.csrf)){fail(res,403,'Request verification failed. Refresh the page.');return;}
   }
   if(req.method==='POST'&&req.path==='/auth/logout'){store.logout(token);setCookie(res,COOKIE,'',0);setCookie(res,CSRF,'',0,false);res.redirect(303,'/login');return;}
   if(req.method==='POST'&&req.path==='/auth/password'){
    if(req.body.password!==req.body.confirm){fail(res,400,'Passwords do not match.');return;}store.changePassword(token,String(req.body.password||''),String(req.body.current||''));setCookie(res,COOKIE,'',0);setCookie(res,CSRF,'',0,false);res.type('html').send(page('Password saved','<section class="card auth"><h1>Your password is saved</h1><p>Your temporary password and earlier sessions are no longer valid. Sign in with your permanent password.</p><a class="button" href="/login">Sign in</a></section>'));return;
   }
   if(req.method==='GET'&&req.path==='/account/password'){res.type('html').send(page('Choose your password',`<section class="card auth"><h1>${session.restricted?'Choose your permanent password':'Change your password'}</h1><p>Use at least 14 characters. This change signs out all sessions. Do not share your new password with anyone.</p><form method="post" action="/auth/password">${csrf(session.csrf)}${session.restricted?'':input('current','Current password','password','required autocomplete="current-password"')}${input('password','New password','password','required minlength="14" maxlength="256" autocomplete="new-password"')}${input('confirm','Confirm new password','password','required minlength="14" maxlength="256" autocomplete="new-password"')}<button data-eve-action-id="auth.password.change">Save permanent password</button></form></section>`));return;}
   if(session.restricted||user.mustChangePassword){if(req.path.startsWith('/api/'))res.status(403).json({error:'PASSWORD_CHANGE_REQUIRED'});else res.redirect('/account/password');return;}
   if(req.method==='GET'&&req.path==='/api/access/session'){res.json({user:safeUser(user),csrf:session.csrf});return;}
   if(req.method==='POST'&&req.path==='/api/portal/intake'){
    if(internal(user)||!user.tenantId){res.status(403).json({error:'CUSTOMER_TENANT_REQUIRED'});return;}
    const tenant=store.read().tenants.find(row=>row.id===user.tenantId);
    if(!tenant){res.status(403).json({error:'CUSTOMER_TENANT_REQUIRED'});return;}
    (req as any).eveCustomerUpload={tenantId:tenant.id,workspaceIds:[...tenant.workspaceIds],userId:user.id,email:user.email};
    req.url='/api/documents/upload';
    next();return;
   }
   if(req.method==='POST'&&req.path==='/auth/revoke-all'){store.revoke(user.id,user.id);setCookie(res,COOKIE,'',0);res.redirect(303,'/login');return;}
   if(req.method==='GET'&&req.path==='/account'){const sessions=store.read().sessions.filter(s=>s.userId===user.id&&s.expiresAt>Date.now());res.type('html').send(page('My account',`<h1>My account</h1><section class="card"><h2>${e(user.email)}</h2><p>Role: ${e(user.role)} · Professional signing authority: not granted by this account.</p><a class="button" href="/account/password">Change password</a><form method="post" action="/auth/revoke-all">${csrf(session.csrf)}<button data-eve-action-id="auth.sessions.revoke">Sign out all sessions</button></form>${table(['Started','Expires'],sessions.map(s=>[s.createdAt,new Date(s.expiresAt).toISOString()]))}</section>`,navigation(user,session.csrf)));return;}
   if(req.path.startsWith('/auth/admin/')){
    if(!admin(user)||req.method!=='POST'){fail(res,403,'Platform administrator access required.');return;}
    let secret='',email='';
    if(req.path==='/auth/admin/invite'){const r=store.invite(String(req.body.email||''),req.body.role,req.body.tenantId||null,user.id);secret=r.temporaryPassword;email=r.user.email;}
    else if(req.path==='/auth/admin/reset'){const target=store.read().users.find(u=>u.id===req.body.userId);if(!target||target.id===user.id){fail(res,400,'Use your account password page for your own account.');return;}secret=store.reset(target.id,user.id);email=target.email;}
    else if(req.path==='/auth/admin/revoke'){store.revoke(String(req.body.userId),user.id);res.redirect(303,'/owner/users');return;}
    else if(req.path==='/auth/admin/tenant'){const ids=String(req.body.workspaceIds||'').split(',').map(x=>x.trim()).filter(Boolean);const records=readOwnerEngagements();store.transaction(s=>{if(!String(req.body.name||'').trim()||!ids.length||ids.some(id=>!records.some(r=>r.workspaceId===id&&r.isCustomer)||s.tenants.some(t=>t.workspaceIds.includes(id))))throw new Error('Select unassigned customer workspaces only.');const tenant={id:random(),name:String(req.body.name).slice(0,120),workspaceIds:ids};s.tenants.push(tenant);store.event(s,user.id,'TENANT_CREATED',tenant.id);});res.redirect(303,'/owner/users');return;}
    else {res.sendStatus(404);return;}
    res.type('html').send(page('One-time account setup',`<section class="card auth"><h1>Setup is ready</h1><p>${e(email)}</p><p>This password is shown once. Deliver it privately to the account holder. It expires after 24 hours and is consumed on the first successful sign-in.</p><code>${e(secret)}</code><p><a href="/login">Account sign-in</a></p><a href="/owner/users">Return to users</a></section>`,navigation(user,session.csrf)));return;
   }
   if(req.path.startsWith('/api/support/')){
    if(!internal(user)){res.status(403).json({error:'SUPPORT_ACCESS_DENIED'});return;}
    const state=supportStore.read(),send=(code:number,error:string)=>res.status(code).json({error});
    if(req.method==='GET'&&req.path==='/api/support/cases'){res.json({cases:state.cases.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),messages:state.messages});return;}
    if(req.method==='POST'&&/^\/api\/support\/cases\/[^/]+\/messages$/.test(req.path)){const caseId=req.path.split('/')[4],row=state.cases.find(c=>c.id===caseId);if(!row)return send(404,'SUPPORT_CASE_NOT_FOUND');const body=String(req.body?.body||'').trim();if(!body)return send(422,'SUPPORT_MESSAGE_REQUIRED');const message=supportStore.addMessage({caseId,tenantId:row.tenantId,actorUserId:user.id,actorKind:'OPERATOR',body,visibility:req.body?.internal===true?'INTERNAL_ONLY':'CUSTOMER_VISIBLE'});res.status(201).json({message});return;}
    if(req.method==='POST'&&/^\/api\/support\/cases\/[^/]+\/session$/.test(req.path)){const caseId=req.path.split('/')[4],row=state.cases.find(c=>c.id===caseId);const reason=String(req.body?.reason||'').trim();if(!row)return send(404,'SUPPORT_CASE_NOT_FOUND');if(reason.length<5)return send(422,'SUPPORT_REASON_REQUIRED');const session=supportStore.startSession({operatorUserId:user.id,tenantId:row.tenantId,caseId,reason});res.status(201).json({session});return;}
    if(req.method==='POST'&&/^\/api\/support\/sessions\/[^/]+\/end$/.test(req.path)){try{res.json({session:supportStore.endSession(req.path.split('/')[4],user.id)});}catch{send(404,'SUPPORT_SESSION_NOT_FOUND');}return;}
    if(req.method==='GET'&&/^\/api\/support\/sessions\/[^/]+\/context$/.test(req.path)){const session=state.sessions.find(s=>s.id===req.path.split('/')[4]&&s.operatorUserId===user.id);if(!session||session.endedAt||Date.parse(session.expiresAt)<=Date.now())return send(403,'SUPPORT_SESSION_EXPIRED');const tenant=store.read().tenants.find(t=>t.id===session.tenantId);const rows=tenant?readOwnerEngagements().filter(r=>r.isCustomer&&tenant.workspaceIds.includes(r.workspaceId)):[];const workspaceId=req.query.workspaceId?String(req.query.workspaceId):undefined;const row=workspaceId?rows.find(r=>r.workspaceId===workspaceId):rows[0];if(!row)return send(404,'SUPPORT_TENANT_SCOPE_VIOLATION');supportStore.transaction(s=>supportStore.audit(s,user.id,session.tenantId,'SUPPORT_OBJECT_VIEWED',session.caseId,session.id));res.json({session,context:customerProjection(row)});return;}
    send(404,'SUPPORT_ROUTE_NOT_FOUND');return;
   }
   if(req.path.startsWith('/api/portal/support/')){
    if(internal(user)||!user.tenantId){res.status(403).json({error:'SUPPORT_ACCESS_DENIED'});return;}const tenantId=user.tenantId,state=supportStore.read();const own=(id:string)=>state.cases.find(c=>c.id===id&&c.tenantId===tenantId);
    if(req.method==='GET'&&req.path==='/api/portal/support/cases'){res.json({cases:state.cases.filter(c=>c.tenantId===tenantId),messages:state.messages.filter(m=>{const c=own(m.caseId);return !!c&&m.visibility==='CUSTOMER_VISIBLE';})});return;}
    if(req.method==='POST'&&req.path==='/api/portal/support/cases'){const subject=String(req.body?.subject||'').trim(),severity=['NORMAL','HIGH','URGENT'].includes(req.body?.severity)?req.body.severity:'NORMAL',workspaceId=req.body?.workspaceId?String(req.body.workspaceId):null;const valid=customerData(user,store).some(r=>r.workspaceId===workspaceId);if(!subject||subject.length>240||workspaceId&&!valid){res.status(422).json({error:'SUPPORT_CASE_INVALID'});return;}res.status(201).json({case:supportStore.createCase({tenantId,workspaceId,subject,severity,createdByUserId:user.id})});return;}
    if(req.method==='POST'&&/^\/api\/portal\/support\/cases\/[^/]+\/messages$/.test(req.path)){const caseId=req.path.split('/')[5],body=String(req.body?.body||'').trim();if(!own(caseId))return res.status(404).json({error:'SUPPORT_CASE_NOT_FOUND'});if(!body)return res.status(422).json({error:'SUPPORT_MESSAGE_REQUIRED'});res.status(201).json({message:supportStore.addMessage({caseId,tenantId,actorUserId:user.id,actorKind:'CUSTOMER',body,visibility:'CUSTOMER_VISIBLE'})});return;}
    res.status(404).json({error:'SUPPORT_CASE_NOT_FOUND'});return;
   }
   if(req.path==='/owner'||req.path.startsWith('/owner/')){
    if(!internal(user)){fail(res,403,'Owner or internal operator access required.');return;}
    const parts=req.path.split('/').filter(Boolean).slice(1),section=parts[0]||'overview',resourceId=parts[1]||'',extra=parts[2];
    if(extra||!ownerSections.includes(section)||resourceId&&!['customers','support'].includes(section)){res.sendStatus(404);return;}
    if(['users','audit'].includes(section)&&!admin(user)){fail(res,403,'Platform administrator access required.');return;}
    const all=readOwnerEngagements(),state=store.read(),tenantCustomer=(row:any)=>row.isCustomer||state.tenants.some(tenant=>tenant.workspaceIds.includes(row.workspaceId)),ownerNav=ownerSections.filter(s=>admin(user)||!['users','audit'].includes(s)).map(s=>`<a href="/owner/${s}">${e(s==='users'?'Users & access':s==='exceptions'?'Exceptions / review':s==='university'?'Eve University':s)}</a>`).join('');
    const rows=(rs:any[])=>table(['Company','Workspace','Status','Documents','Eligible facts','Last activity'],rs.map(r=>[r.clientName,r.workspaceId,r.status,r.documentsCount,r.canonicalFactsCount,r.lastActivityAt]));
    const render=(title:string,content:string)=>{res.type('html').send(page(title,`<div class="eyebrow">Owner command center · isolated acceptance</div><h1>${e(title)}</h1><nav class="control-nav">${ownerNav}</nav>${content}`,navigation(user,session.csrf)));};

    if(section==='customers'&&resourceId){
      const customer=all.find(row=>tenantCustomer(row)&&row.workspaceId===resourceId);if(!customer){res.sendStatus(404);return;}
      const customerReports=(customer.reports||[]).map((report:any)=>[report.reportId,report.version,report.status,Object.keys(report.formats||{}).join(', ')||'No artifact']);
      render('Customer detail',`<p>${controlLink('/owner/customers','← All customers')}</p><section class="card customer-summary"><div><p class="eyebrow">Customer workspace</p><h2>${e(customer.clientName)}</h2><p>${e(customer.workspaceId)} · ${e(customer.period)} · ${caseBadge(String(customer.status))}</p></div><div class="metric-grid"><div><b>${e(customer.documentsCount)}</b><span>Documents</span></div><div><b>${e(customer.canonicalFactsCount)}</b><span>Approved facts</span></div><div><b>${e(customer.openPbcCount)}</b><span>Open PBC</span></div><div><b>${e(customer.openReviewNotesCount)}</b><span>Open findings</span></div></div></section><section class="card"><h2>Documents</h2>${table(['Document','Type','SHA-256','State','Uploaded'],customer.documents.map((document:any)=>[document.filename||'Not recorded',document.mimeType||'Not recorded',document.sha256||'Not recorded',document.extractionState||'Recorded',document.uploadedAt||'Not recorded']))}</section><section class="card"><h2>Supported accounting values</h2>${table(['Metric','Value','Period','Currency'],customer.facts.map((fact:any)=>[fact.label||fact.metric,fact.value,fact.reportingPeriod||fact.period,fact.currency||'Not recorded']))}</section><section class="card"><h2>Exceptions / review</h2>${table(['Issue','Status'],customer.findings.map((finding:any)=>[finding.title||finding.message,finding.status]))}</section><section class="card"><h2>Reports</h2>${table(['Report','Version','State','Formats'],customerReports)}</section>${rawAccountingPanels(rawInputHermesContinuationService.getAllContinuations().filter(row=>row.workspaceId===customer.workspaceId),'Academy Accounting Case')}`);return;
    }

    if(section==='support'&&resourceId){
      const support=supportStore.read(),supportCase=support.cases.find(row=>row.id===resourceId);if(!supportCase){res.sendStatus(404);return;}
      const tenant=state.tenants.find(row=>row.id===supportCase.tenantId),activeSession=support.sessions.find(row=>row.caseId===supportCase.id&&row.operatorUserId===user.id&&row.tenantId===supportCase.tenantId&&!row.endedAt&&Date.parse(row.expiresAt)>Date.now()),workspaceAllowed=!!(activeSession&&supportCase.workspaceId&&tenant?.workspaceIds.includes(supportCase.workspaceId)),customer=workspaceAllowed?all.find(row=>row.isCustomer&&row.workspaceId===supportCase.workspaceId):undefined,messages=support.messages.filter(row=>row.caseId===supportCase.id);
      const conversation=messages.length?messages.map(message=>`<article class="message ${message.visibility==='INTERNAL_ONLY'?'internal-note':''}"><div><b>${e(message.actorKind==='CUSTOMER'?'Customer':'Eve support')}</b><time>${previewDate(message.createdAt)}</time></div><p>${e(message.body)}</p><small>${e(message.visibility==='INTERNAL_ONLY'?'Internal note — not customer visible':'Customer visible')}</small></article>`).join(''):'<p>No messages are recorded for this case.</p>';
      const context=customer?`<div class="metric-grid compact"><div><b>${e(customer.documentsCount)}</b><span>Documents</span></div><div><b>${e(customer.canonicalFactsCount)}</b><span>Approved facts</span></div><div><b>${e(customer.openPbcCount)}</b><span>Open PBC</span></div><div><b>${e(customer.openReviewNotesCount)}</b><span>Open findings</span></div></div><p><b>Workspace:</b> ${e(customer.workspaceId)}<br><b>Period:</b> ${e(customer.period)}<br><b>Processing state:</b> ${e(customer.status)}<br><b>Last activity:</b> ${previewDate(customer.lastActivityAt)}</p>${controlLink(`/owner/customers/${encodeURIComponent(customer.workspaceId)}`,'Open customer detail')}`:activeSession?'<p>The linked workspace is not available in this tenant. No cross-tenant fallback is permitted.</p>':'<p>Customer context remains hidden until this operator has an active, time-limited, read-only session for this case.</p>';
      render('Support case',`<p>${controlLink('/owner/support','← Support inbox')}</p><section class="card case-header"><div><p class="eyebrow">${e(tenant?.name||'Restricted tenant')}</p><h2>${e(supportCase.subject)}</h2><p>${caseBadge(supportCase.severity)} ${caseBadge(supportCase.status)} · Updated ${previewDate(supportCase.updatedAt)}</p></div>${activeSession?`<div class="session-banner"><b>Support session active</b><span>Read-only · Tenant scoped · Expires ${previewDate(activeSession.expiresAt)}</span></div>`:'<div class="session-banner inactive"><b>No active support session</b><span>Support remains tenant scoped and read-only by default.</span></div>'}</section><div class="support-case-grid"><section class="card"><h2>Conversation</h2>${conversation}</section><section class="card"><h2>Customer context</h2>${context}</section><section class="card"><h2>Operator assist</h2><p><b>Mode:</b> Read-only support</p><p><b>Reason:</b> ${e(activeSession?.reason||'A support session has not been started.')}</p><p><b>Diagnostics:</b> Build metadata, workspace identity, and saved evidence may be inspected only through the existing scoped routes. Credentials, tokens, and raw environment values are never displayed.</p><p class="muted">No elevated action is enabled in this acceptance preview.</p></section></div>`);return;
    }

    let content='';
    if(section==='overview')content=`<div class="grid">${[['Customers',all.filter(tenantCustomer).length],['Engagements',all.length],['Documents',all.reduce((n,r)=>n+r.documentsCount,0)],['Accounts',state.users.length]].map(([k,v])=>`<section class="card"><p>${k}</p><div class="stat">${v}</div></section>`).join('')}</div><section class="card"><h2>Current work</h2>${rows(all)}<a href="/workspace?view=practice-engagements">Open engagements</a></section>`;
    if(section==='customers'){const customers=all.filter(tenantCustomer);content=`<section class="card"><h2>Customers</h2>${controlTable(['Customer','Workspace','Status','Documents','Eligible facts','Action'],customers.map(row=>[e(row.clientName),e(row.workspaceId),caseBadge(String(row.status)),e(row.documentsCount),e(row.canonicalFactsCount),controlLink(`/owner/customers/${encodeURIComponent(row.workspaceId)}`,'Open customer')]))}<h2>Customer organizations</h2>${table(['Organization','Assigned workspaces','Users'],state.tenants.map(t=>[t.name,t.workspaceIds.join(', '),state.users.filter(u=>u.tenantId===t.id).length]))}</section>`;}
    if(section==='support'){const support=supportStore.read(),openCases=support.cases.filter(row=>!['CLOSED','RESOLVED'].includes(row.status)).length;content=`<section class="card"><div class="section-heading"><div><p class="eyebrow">Operator assist</p><h2>Support inbox</h2></div><span class="count-badge">${e(openCases)} open</span></div>${controlTable(['Customer','Subject','Severity','Status','Assigned','Updated','Action'],support.cases.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(row=>[e(state.tenants.find(t=>t.id===row.tenantId)?.name||'Restricted tenant'),e(row.subject),caseBadge(row.severity),caseBadge(row.status),e(row.assignedOperatorUserId||'Unassigned'),previewDate(row.updatedAt),controlLink(`/owner/support/${encodeURIComponent(row.id)}`,'Open case')]))}<p>Support sessions are read-only, tenant-bound, time-limited, and require a stated reason. Support access does not grant professional approval or signing authority.</p></section>`;}
    if(section==='engagements')content=`<section class="card"><h2>Engagements</h2>${table(['Client','Period','Stage','Documents','Evidence','Review state','Report state','Last update'],all.map(r=>[r.clientName,r.period,r.status,r.documentsCount,r.canonicalFactsCount,'Review required where flagged',r.reports?.[0]?.status||'No report',r.lastActivityAt]))}</section>`;
    if(section==='documents')content=`<section class="card"><h2>Documents</h2>${table(['File','Client','Period','SHA / verification','Extraction state','Uploaded'],all.flatMap(r=>r.documents.map((d:any)=>[d.filename,r.clientName,r.period,d.sha256||'Not recorded',d.extractionState||'Recorded',d.uploadedAt||r.lastActivityAt])))}</section>`;
    if(section==='exceptions')content=`<section class="card"><h2>Exceptions / review</h2>${table(['Client','Issue','Status','Action'],all.flatMap(r=>r.findings.filter((f:any)=>f.status!=='RESOLVED').map((f:any)=>[r.clientName,f.title||f.message,f.status,'Open evidence / request clarification'])))}<p>Resolution remains governed by the existing evidence and professional-review rules.</p></section>`;
    if(section==='university')content=universityDashboard();
    if(section==='academy')content=`<section class="card"><p>Academy remains operated by the existing Hermes scheduler. This screen reads saved engagement evidence; it does not start another scheduler.</p>${rows(all.filter(r=>r.classification==='ACADEMY'))}<a class="button" href="/workspace?view=eve-academy">Open Academy evidence</a><p>Live Hermes scheduler and browser learning files are retained on Hermes. A remote status feed is not yet connected to this control center.</p></section>`;
    if(section==='agents')content=`<section class="card">${table(['Company','Agent','Status','Model','Execution'],all.flatMap(r=>(r.continuation?.specialistSummary?.jobs||[]).map((j:any)=>[r.clientName,j.agentId,j.status,j.provenance?.actualModel||j.provenance?.model||'Not recorded',j.agentExecutionId])))}<a href="/workspace?view=eve-intelligence">Open agent evidence</a></section>`;
    if(section==='reports')content=`<section class="card"><h2>Reports</h2>${table(['Company','Report','Version','Review state','Formats'],all.flatMap(r=>r.reports.map((p:any)=>[r.clientName,p.reportId,p.version,p.status,Object.keys(p.formats).join(', ')])))}<a class="button" href="/workspace?view=practice-engagements">Open engagement to review and download</a></section>`;
    if(section==='system')content=`<section class="card"><h2>Application</h2><p>Source: <code class="build-metadata">${e(fs.existsSync(path.join(process.cwd(),'dist','access-build.json'))?fs.readFileSync(path.join(process.cwd(),'dist','access-build.json'),'utf8'):'Build metadata unavailable')}</code></p><a class="button" href="/workspace?view=admin-health">Open system health</a><p>Existing extraction worker, Hermes, OpenClaw and local AI remain in place. Provider administration stays outside customer access.</p></section>`;
    if(section==='audit')content=`<section class="card">${table(['Time','Actor','Event','Subject'],state.audit.slice(-250).reverse().map(a=>[a.at,a.actor,a.event,a.subject]))}<p>Authentication and account administration events. <a href="/workspace?view=admin-audit-logs">Open accounting activity</a>.</p></section>`;
    if(section==='users')content=`<section class="card"><h2>Accounts</h2>${table(['Email','Role','Tenant','Password setup','Active sessions'],state.users.map(u=>[u.email,u.role,u.tenantId||'Platform',u.mustChangePassword?'Required':'Complete',state.sessions.filter(s=>s.userId===u.id&&s.expiresAt>Date.now()).length]))}<p>Account roles never imply a professional license or signing authority.</p></section><div class="grid"><section class="card"><h2>Invite user</h2><form method="post" action="/auth/admin/invite">${csrf(session.csrf)}${input('email','Email','email','required')}<label for="role">Role</label><select id="role" name="role">${roles.map(r=>`<option>${r}</option>`).join('')}</select><label for="tenantId">Customer organization</label><select id="tenantId" name="tenantId"><option value="">Platform role only</option>${state.tenants.map(t=>`<option value="${e(t.id)}">${e(t.name)}</option>`).join('')}</select><button data-eve-action-id="access.invite">Create one-time invitation</button></form></section><section class="card"><h2>Assign customer organization</h2><form method="post" action="/auth/admin/tenant">${csrf(session.csrf)}${input('name','Organization name','text','required')}${input('workspaceIds','Customer workspace IDs, comma-separated','text','required')}<button data-eve-action-id="access.tenant.assign">Create organization</button></form></section><section class="card"><h2>Account recovery and sessions</h2><form method="post" action="/auth/admin/reset">${csrf(session.csrf)}<label for="userId">Account</label><select id="userId" name="userId">${state.users.filter(u=>u.id!==user.id).map(u=>`<option value="${e(u.id)}">${e(u.email)}</option>`).join('')}</select><button data-eve-action-id="access.password.reset">Issue one-time reset</button><button formaction="/auth/admin/revoke">Revoke all sessions</button></form></section></div>`;
    render(section==='users'?'Users & access':section==='exceptions'?'Exceptions / review':section.charAt(0).toUpperCase()+section.slice(1),content);return;
   }
   if(req.path==='/portal'||req.path==='/portal/support'||req.path.startsWith('/api/portal/')){
    const data=internal(user)?[]:customerData(user,store);if(req.method!=='GET'){res.status(403).json({error:'ACTION_NOT_PERMITTED'});return;}
    if(req.path==='/api/portal/engagements'){res.json({engagements:data.map(summary)});return;}
    if(req.path.startsWith('/api/portal/engagements/')){const id=req.path.slice('/api/portal/engagements/'.length);const row=data.find(r=>r.engagementId===id);if(!row){res.sendStatus(404);return;}res.json(customerProjection(row));return;}
    if(req.path==='/api/portal/report'){
     const row=data.find(r=>r.engagementId===req.query.engagementId),report=row?.reports.find((p:any)=>p.reportId===req.query.reportId&&p.version===req.query.version);const format=String(req.query.format||'pdf').toLowerCase(),formatKey=format==='csv'?'csv':format;const names:any={pdf:`audit_report_${report?.reportId}_${report?.version}.pdf`,xlsx:`audit_workbook_${report?.reportId}_${report?.version}.xlsx`,csv:`lead_schedules_${report?.reportId}_${report?.version}.csv`,json:`audit_package_${report?.reportId}_${report?.version}.json`};if(!report||!['pdf','xlsx','csv','json'].includes(format)||!report.formats[formatKey]||![report.reportId,report.version].every(v=>/^[a-zA-Z0-9_.-]+$/.test(v))){res.sendStatus(404);return;}const root=path.resolve(process.env.HERMES_REPORTS_DIR||path.join(process.cwd(),'storage','reports')),target=path.resolve(root,names[format]);if(path.dirname(target)!==root||!fs.existsSync(target)){res.sendStatus(404);return;}res.setHeader('X-Artifact-SHA256',report.formats[formatKey].sha256);res.download(target);return;
    }
    if(req.path==='/portal/support'){
     if(internal(user)||!user.tenantId){res.status(403).json({error:'SUPPORT_ACCESS_DENIED'});return;}
     const support=supportStore.read(),tenantId=user.tenantId,cases=support.cases.filter(row=>row.tenantId===tenantId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),caseIds=new Set(cases.map(row=>row.id)),messages=support.messages.filter(row=>caseIds.has(row.caseId)&&row.visibility==='CUSTOMER_VISIBLE');
     const caseCards=cases.length?cases.map(row=>{const caseMessages=messages.filter(message=>message.caseId===row.id),workspace=data.find(item=>item.workspaceId===row.workspaceId);return `<article class="card support-history"><div class="section-heading"><div><p class="eyebrow">${e(workspace?.clientName||'Organization support')}</p><h2>${e(row.subject)}</h2></div><div>${caseBadge(row.severity)} ${caseBadge(row.status)}</div></div><p><b>Last updated:</b> ${previewDate(row.updatedAt)}${workspace?` · <b>Workspace:</b> ${e(workspace.workspaceId)}`:''}</p><div class="message-list">${caseMessages.length?caseMessages.map(message=>`<article class="message customer-message"><div><b>${e(message.actorKind==='CUSTOMER'?'You':'Eve support')}</b><time>${previewDate(message.createdAt)}</time></div><p>${e(message.body)}</p></article>`).join(''):'<p>No customer-visible updates have been recorded for this case.</p>'}</div></article>`;}).join(''):'<section class="card"><h2>No support cases yet</h2><p>When your organization opens a request, it will appear here with only customer-visible replies.</p></section>';
     res.type('html').send(page('Customer Help & Support',`<div class="eyebrow">Customer workspace</div><h1>Customer Help &amp; Support</h1><section class="card help-intro"><h2>Support that stays inside your organization</h2><p>Use this space to follow your accounting support requests. Eve support is tenant scoped: it can use only a separately started, time-limited, read-only session for the case at hand. Support access does not approve work, change records, or grant professional signing authority.</p><p class="muted">This isolated acceptance preview shows synthetic case activity. The existing tenant-scoped case and reply APIs remain protected; this visual page does not add a new write path.</p></section><section class="support-history-list"><h2>Your support history</h2>${caseCards}</section>`,navigation(user,session.csrf)));return;
    }
    if(req.path!=='/portal'){res.sendStatus(404);return;}
    const raw=rawInputHermesContinuationService.getAllContinuations();
    res.type('html').send(page('My organization',`<div class="eyebrow">Customer workspace</div><h1>Your accounting work</h1><p>Only workspaces assigned to your organization appear here. Reports and workpapers are AI-prepared drafts unless separately approved through the professional review process.</p>${data.length?data.map(r=>{const p=customerProjection(r),continuations=raw.filter(row=>row.workspaceId===r.workspaceId);return `<section class="card"><h2>${e(r.clientName)}</h2><p>${e(r.period)} · ${e(r.status)}</p><h3>Documents</h3><form method="post" enctype="multipart/form-data" action="/api/portal/intake">${csrf(session.csrf)}<input type="hidden" name="workspaceId" value="${e(r.workspaceId)}"><input type="hidden" name="uploadIntent" value="ATTACH_TO_EXISTING_PROJECT"><input type="file" name="files" required><button data-eve-action-id="customer.documents.upload">Upload document</button></form>${table(['Document','SHA-256'],p.documents.map((d:any)=>[d.filename,d.sha256]))}<h3>Raw accounting continuation</h3>${table(['Document','State','Latest stage','Outcome'],continuations.map(row=>[row.documentKind,row.status,row.executions.at(-1)?.stage||'Queued',row.executions.filter(x=>x.outcomeCode).at(-1)?.outcomeCode||'Pending']))}<h3>Supported accounting values</h3>${table(['Metric','Value','Period','Currency','Scale','Source'],p.facts.map((f:any)=>[f.label||f.metric,f.value,f.reportingPeriod||f.period,f.currency,f.scale||f.unit||'As recorded',f.sourceText]))}<h3>Shared findings</h3>${table(['Finding','Status'],p.findings.map((f:any)=>[f.title||f.message,f.status]))}<h3>Draft reports</h3>${p.reports.map((v:any)=>{const formats=['pdf','xlsx','csv','json'].filter(format=>v.formats.includes(format));return formats.length?`<p>${e(v.title)} — ${e(v.version)}: ${formats.map(format=>`<a href="/api/portal/report?engagementId=${encodeURIComponent(r.engagementId)}&reportId=${encodeURIComponent(v.reportId)}&version=${encodeURIComponent(v.version)}&format=${format}">${format.toUpperCase()}</a>`).join(' · ')}</p>`:''}).join('')}${rawAccountingPanels(continuations,'Customer Accounting Evidence')}</section>`;}).join(''):'<section class="card"><h2>No organization work assigned yet</h2><p>Your administrator must explicitly assign your company workspace before any accounting data is visible.</p></section>'}`,navigation(user,session.csrf)));return;
   }
   // Default deny is deliberate: customers cannot reach any legacy/global endpoint,
   // including assets, reviewer APIs, raw evidence, infrastructure or write paths.
   if(!internal(user)){res.status(403).json({error:'TENANT_ROUTE_NOT_PERMITTED'});return;}
   if(!['GET','HEAD','OPTIONS'].includes(req.method))store.transaction(s=>store.event(s,user.id,'PRODUCT_ACTION',req.method+' '+req.path.slice(0,180)));
   (req as any).user={id:user.id,sessionId:session.hash,role:user.role,claims:['INTERNAL_OPERATOR'],isHuman:true};
   next();
  }catch(err:any){const known=/Invalid|Tenant|required|already|password|Account|Select|LOGIN_THROTTLED/.test(err.message);fail(res,err.message==='LOGIN_THROTTLED'?429:known?400:503,known?err.message:'Access service unavailable. Please try again.');}
 });
 return router;
}
