import express, { type Request, type Response, type NextFunction } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { IdentityStore, admin, internal, random, digest, roles, safeUser, type User } from './identityStore.js';
import { page, escape as e, input, csrf, table, mark, marketing } from './portalPages.js';
import { readOwnerEngagements } from '../cpaOrganization/ownerEngagementReadModel.js';
const COOKIE='__Host-eve_session', PRE='__Host-eve_login_csrf';
export const identityStore=new IdentityStore();
const cookie=(req:Request,name:string)=>{try{return decodeURIComponent((req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'');}catch{return '';}};
const setCookie=(res:Response,name:string,value:string,age=43200)=>res.append('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=${age}`);
const safeOrigin=(req:Request)=>{if(req.get('sec-fetch-site')==='cross-site')return false;const origin=req.get('origin');if(!origin)return false;try{return new URL(origin).origin===`https://${req.get('host')}`;}catch{return false;}};
const fail=(res:Response,status:number,message:string)=>res.status(status).type('html').send(page('Access',`<section class="card auth"><h1>Unable to continue</h1><p class="error">${e(message)}</p><a href="/login">Sign in</a></section>`));
const summary=(r:any)=>({workspaceId:r.workspaceId,engagementId:r.engagementId,clientName:r.clientName,status:r.status,period:r.period,documentsCount:r.documentsCount,canonicalFactsCount:r.canonicalFactsCount});
function customerData(u:User,store:IdentityStore){const tenant=store.read().tenants.find(t=>t.id===u.tenantId);return tenant?readOwnerEngagements().filter(r=>r.isCustomer&&tenant.workspaceIds.includes(r.workspaceId)):[];}
function customerProjection(r:any){return {...summary(r),periods:r.periods,numericVariance:r.numericVariance,documents:r.documents.map((d:any)=>({id:d.id,filename:d.filename,sha256:d.sha256,mimeType:d.mimeType})),facts:r.facts.filter((f:any)=>f.status==='APPROVED'&&(f.verificationStatus||f.verification_status)==='VERIFIED'&&(f.evidenceStatus||f.evidence_status)==='CONFIRMED').map((f:any)=>Object.fromEntries(['id','label','metric','value','period','reportingPeriod','currency','unit','scale','sourceText','documentId'].map(k=>[k,f[k]]))),findings:r.findings.filter((f:any)=>f.customerVisible===true).map((f:any)=>({id:f.id,title:f.title,message:f.message,status:f.status})),reports:r.reports.map((p:any)=>({reportId:p.reportId,version:p.version,status:p.status,title:p.title,formats:Object.keys(p.formats)}))};}
const ownerSections=['overview','customers','academy','agents','reports','users','system','audit'];
function navigation(u:User,token:string){return `${internal(u)?'<a href="/owner">Control center</a><a href="/">Accounting workspace</a>':'<a href="/portal">My organization</a>'}<a href="/account">My account</a><form class="inline" method="post" action="/auth/logout">${csrf(token)}<button data-eve-action-id="auth.logout">Log out</button></form>`;}
export function createAccessPortal(store=identityStore){
 const router=express.Router();
 router.use((req,res,next)=>{if(['/login','/account','/owner','/portal','/public','/password-help','/auth'].some(p=>req.path===p||req.path.startsWith(p+'/')))res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");res.set({'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});if(req.path.startsWith('/auth/')){express.urlencoded({extended:false,limit:'16kb'})(req,res,err=>err?fail(res,400,'Invalid request.'):next());}else next();});
 router.use((req,res,next)=>{
  try {
   if(req.method==='GET'&&req.path==='/brand/eve.svg'){res.type('image/svg+xml').send(mark);return;}
   const hostname=(req.hostname||'').toLowerCase();
   if(req.method==='GET'&&req.path==='/'){
    if(hostname==='www.evesbookkeeping.com'){res.redirect(308,'https://evesbookkeeping.com');return;}
    if(hostname==='evesbookkeeping.com'){res.type('html').send(marketing('home'));return;}
    if(hostname==='owner.evesbookkeeping.com'){res.redirect('/owner');return;}
    if(hostname==='app.evesbookkeeping.com'){res.redirect('/portal');return;}
   }
   if(req.method==='GET'&&(req.path==='/public'||req.path.startsWith('/public/'))){const html=marketing(req.path.slice(8)||'home');if(!html){res.sendStatus(404);return;}res.type('html').send(html);return;}
   if(req.method==='GET'&&req.path==='/login'){const token=random();setCookie(res,PRE,token,1800);res.type('html').send(page('Sign in',`<section class="card auth"><div class="eyebrow">Secure workspace</div><h1>Welcome to Eve</h1><p>Sign in with your account. New invitations require a permanent password before opening your workspace.</p><form method="post" action="/auth/login">${csrf(token)}${input('email','Email','email','required autocomplete="username" maxlength="254"')}${input('password','Password','password','required autocomplete="current-password" maxlength="256"')}<button data-eve-action-id="auth.login">Sign in</button></form><a href="/password-help">Forgot your password?</a><p><a href="/operator-login">Temporary development access</a></p></section>`));return;}
   if(req.method==='GET'&&req.path==='/password-help'){res.type('html').send(page('Account recovery',`<section class="card auth"><h1>Recover your account</h1><p>Ask your platform administrator for a new one-time setup password. Resetting your account revokes existing sessions. Your permanent password is never disclosed.</p><p>Owner recovery is available through the protected deployment administration command. Automatic email recovery is not enabled until a delivery provider is configured.</p><a href="/login">Back to sign in</a></section>`));return;}
   if(req.method==='POST'&&req.path==='/auth/login'){
    if(!safeOrigin(req)||!cookie(req,PRE)||digest(String(req.body.csrf||''))!==digest(cookie(req,PRE))){fail(res,403,'Sign-in request expired. Reload the sign-in page.');return;}
    const result=store.login(String(req.body.email||''),String(req.body.password||''),req.socket.remoteAddress||'unknown');if(!result){fail(res,401,'Email or password was not accepted.');return;}setCookie(res,COOKIE,result.token,result.session.restricted?1800:43200);setCookie(res,PRE,'',0);res.redirect(303,result.session.restricted?'/account/password':internal(result.user)?'/owner':'/portal');return;
   }
   const token=cookie(req,COOKIE),ctx=store.session(token);
   if(!ctx){if(req.path.startsWith('/auth/')||['/owner','/portal','/account'].some(p=>req.path===p||req.path.startsWith(p+'/'))||req.path.startsWith('/api/portal/')||req.path==='/api/access/session'){if(req.path.startsWith('/api/'))res.status(401).json({error:'SIGN_IN_REQUIRED'});else res.redirect('/login');return;}next();return;}
   const {user,session}=ctx;(req as any).eveIdentity=ctx;
   if(!['GET','HEAD','OPTIONS'].includes(req.method)){
    if(!safeOrigin(req)||digest(String(req.get('x-eve-csrf')||req.body?.csrf||''))!==digest(session.csrf)){fail(res,403,'Request verification failed. Refresh the page.');return;}
   }
   if(req.method==='POST'&&req.path==='/auth/logout'){store.logout(token);setCookie(res,COOKIE,'',0);res.redirect(303,'/login');return;}
   if(req.method==='POST'&&req.path==='/auth/password'){
    if(req.body.password!==req.body.confirm){fail(res,400,'Passwords do not match.');return;}store.changePassword(token,String(req.body.password||''),String(req.body.current||''));setCookie(res,COOKIE,'',0);res.type('html').send(page('Password saved','<section class="card auth"><h1>Your password is saved</h1><p>Your temporary password and earlier sessions are no longer valid. Sign in with your permanent password.</p><a class="button" href="/login">Sign in</a></section>'));return;
   }
   if(req.method==='GET'&&req.path==='/account/password'){res.type('html').send(page('Choose your password',`<section class="card auth"><h1>${session.restricted?'Choose your permanent password':'Change your password'}</h1><p>Use at least 14 characters. This change signs out all sessions. Do not share your new password with anyone.</p><form method="post" action="/auth/password">${csrf(session.csrf)}${session.restricted?'':input('current','Current password','password','required autocomplete="current-password"')}${input('password','New password','password','required minlength="14" maxlength="256" autocomplete="new-password"')}${input('confirm','Confirm new password','password','required minlength="14" maxlength="256" autocomplete="new-password"')}<button data-eve-action-id="auth.password.change">Save permanent password</button></form></section>`));return;}
   if(session.restricted||user.mustChangePassword){if(req.path.startsWith('/api/'))res.status(403).json({error:'PASSWORD_CHANGE_REQUIRED'});else res.redirect('/account/password');return;}
   if(req.method==='GET'&&req.path==='/api/access/session'){res.json({user:safeUser(user),csrf:session.csrf});return;}
   if(req.method==='POST'&&req.path==='/auth/revoke-all'){store.revoke(user.id,user.id);setCookie(res,COOKIE,'',0);res.redirect(303,'/login');return;}
   if(req.method==='GET'&&req.path==='/account'){const sessions=store.read().sessions.filter(s=>s.userId===user.id&&s.expiresAt>Date.now());res.type('html').send(page('My account',`<h1>My account</h1><section class="card"><h2>${e(user.email)}</h2><p>Role: ${e(user.role)} · Professional signing authority: not granted by this account.</p><a class="button" href="/account/password">Change password</a><form method="post" action="/auth/revoke-all">${csrf(session.csrf)}<button data-eve-action-id="auth.sessions.revoke">Sign out all sessions</button></form>${table(['Started','Expires'],sessions.map(s=>[s.createdAt,new Date(s.expiresAt).toISOString()]))}</section>`,navigation(user,session.csrf)));return;}
   if(req.path.startsWith('/auth/admin/')){
    if(!admin(user)||req.method!=='POST'){fail(res,403,'Platform administrator access required.');return;}
    let secret='',email='';
    if(req.path==='/auth/admin/invite'){const r=store.invite(String(req.body.email||''),req.body.role,req.body.tenantId||null,user.id);secret=r.temporaryPassword;email=r.user.email;}
    else if(req.path==='/auth/admin/reset'){const target=store.read().users.find(u=>u.id===req.body.userId);if(!target||target.id===user.id){fail(res,400,'Use your account password page for your own account.');return;}secret=store.reset(target.id,user.id);email=target.email;}
    else if(req.path==='/auth/admin/revoke'){store.revoke(String(req.body.userId),user.id);res.redirect(303,'/owner/users');return;}
    else if(req.path==='/auth/admin/tenant'){const ids=String(req.body.workspaceIds||'').split(',').map(x=>x.trim()).filter(Boolean);const records=readOwnerEngagements();store.transaction(s=>{if(!String(req.body.name||'').trim()||!ids.length||ids.some(id=>!records.some(r=>r.workspaceId===id&&r.isCustomer)||s.tenants.some(t=>t.workspaceIds.includes(id))))throw new Error('Select unassigned customer workspaces only.');const tenant={id:random(),name:String(req.body.name).slice(0,120),workspaceIds:ids};s.tenants.push(tenant);store.event(s,user.id,'TENANT_CREATED',tenant.id);});res.redirect(303,'/owner/users');return;}
    else {res.sendStatus(404);return;}
    res.type('html').send(page('One-time account setup',`<section class="card auth"><h1>Setup is ready</h1><p>${e(email)}</p><p>This password is shown once. Deliver it privately to the account holder. It expires after 24 hours and is consumed on the first successful sign-in.</p><code>${e(secret)}</code><p><a href="/login">Account sign-in</a></p><a href="/owner/users">Return to users</a></section>`,navigation(user,session.csrf)));return;
   }
   if(req.path==='/owner'||req.path.startsWith('/owner/')){
    if(!internal(user)){fail(res,403,'Owner or internal operator access required.');return;}const section=req.path.split('/')[2]||'overview';if(!ownerSections.includes(section)){res.sendStatus(404);return;}if(['users','audit'].includes(section)&&!admin(user)){fail(res,403,'Platform administrator access required.');return;}
    const all=readOwnerEngagements(),state=store.read();let content='';
    const rows=(rs:any[])=>table(['Company','Workspace','Status','Documents','Eligible facts','Last activity'],rs.map(r=>[r.clientName,r.workspaceId,r.status,r.documentsCount,r.canonicalFactsCount,r.lastActivityAt]));
    if(section==='overview')content=`<div class="grid">${[['Customers',all.filter(r=>r.isCustomer).length],['Engagements',all.length],['Documents',all.reduce((n,r)=>n+r.documentsCount,0)],['Accounts',state.users.length]].map(([k,v])=>`<section class="card"><p>${k}</p><div class="stat">${v}</div></section>`).join('')}</div><section class="card"><h2>Current work</h2>${rows(all)}<a href="/?view=practice-engagements">Open engagements</a></section>`;
    if(section==='customers')content=`<section class="card">${rows(all.filter(r=>r.isCustomer))}<h2>Customer organizations</h2>${table(['Organization','Assigned workspaces','Users'],state.tenants.map(t=>[t.name,t.workspaceIds.join(', '),state.users.filter(u=>u.tenantId===t.id).length]))}</section>`;
    if(section==='academy')content=`<section class="card"><p>Academy remains operated by the existing Hermes scheduler. This screen reads saved engagement evidence; it does not start another scheduler.</p>${rows(all.filter(r=>r.classification==='ACADEMY'))}<a class="button" href="/?view=eve-academy">Open Academy evidence</a><p>Live Hermes scheduler and browser learning files are retained on Hermes. A remote status feed is not yet connected to this control center.</p></section>`;
    if(section==='agents')content=`<section class="card">${table(['Company','Agent','Status','Model','Execution'],all.flatMap(r=>(r.continuation?.specialistSummary?.jobs||[]).map((j:any)=>[r.clientName,j.agentId,j.status,j.provenance?.actualModel||j.provenance?.model||'Not recorded',j.agentExecutionId])))}<a href="/?view=eve-intelligence">Open agent evidence</a></section>`;
    if(section==='reports')content=`<section class="card">${table(['Company','Report','Version','Review state','Formats'],all.flatMap(r=>r.reports.map((p:any)=>[r.clientName,p.reportId,p.version,p.status,Object.keys(p.formats).join(', ')])))}<a class="button" href="/?view=practice-engagements">Open engagement to review and download</a></section>`;
    if(section==='system')content=`<section class="card"><h2>Application</h2><p>Source: ${e(fs.existsSync(path.join(process.cwd(),'dist','access-build.json'))?fs.readFileSync(path.join(process.cwd(),'dist','access-build.json'),'utf8'):'Build metadata unavailable')}</p><a class="button" href="/?view=admin-health">Open system health</a><p>Existing extraction worker, Hermes, OpenClaw and local AI remain in place. Provider administration stays outside customer access.</p></section>`;
    if(section==='audit')content=`<section class="card">${table(['Time','Actor','Event','Subject'],state.audit.slice(-250).reverse().map(a=>[a.at,a.actor,a.event,a.subject]))}<p>Authentication and account administration events. <a href="/?view=admin-audit-logs">Open accounting activity</a>.</p></section>`;
    if(section==='users')content=`<section class="card"><h2>Accounts</h2>${table(['Email','Role','Tenant','Password setup','Active sessions'],state.users.map(u=>[u.email,u.role,u.tenantId||'Platform',u.mustChangePassword?'Required':'Complete',state.sessions.filter(s=>s.userId===u.id&&s.expiresAt>Date.now()).length]))}<p>Account roles never imply a professional license or signing authority.</p></section><div class="grid"><section class="card"><h2>Invite user</h2><form method="post" action="/auth/admin/invite">${csrf(session.csrf)}${input('email','Email','email','required')}<label for="role">Role</label><select id="role" name="role">${roles.map(r=>`<option>${r}</option>`).join('')}</select><label for="tenantId">Customer organization</label><select id="tenantId" name="tenantId"><option value="">Platform role only</option>${state.tenants.map(t=>`<option value="${e(t.id)}">${e(t.name)}</option>`).join('')}</select><button data-eve-action-id="access.invite">Create one-time invitation</button></form></section><section class="card"><h2>Assign customer organization</h2><form method="post" action="/auth/admin/tenant">${csrf(session.csrf)}${input('name','Organization name','text','required')}${input('workspaceIds','Customer workspace IDs, comma-separated','text','required')}<button data-eve-action-id="access.tenant.assign">Create organization</button></form></section><section class="card"><h2>Account recovery and sessions</h2><form method="post" action="/auth/admin/reset">${csrf(session.csrf)}<label for="userId">Account</label><select id="userId" name="userId">${state.users.filter(u=>u.id!==user.id).map(u=>`<option value="${e(u.id)}">${e(u.email)}</option>`).join('')}</select><button data-eve-action-id="access.password.reset">Issue one-time reset</button><button formaction="/auth/admin/revoke">Revoke all sessions</button></form></section></div>`;
    res.type('html').send(page('Owner control center',`<div class="eyebrow">Owner control center</div><h1>${e(section.charAt(0).toUpperCase()+section.slice(1))}</h1><nav>${ownerSections.filter(s=>admin(user)||!['users','audit'].includes(s)).map(s=>`<a href="/owner/${s}">${e(s==='users'?'Users & access':s)}</a>`).join('')}</nav>${content}`,navigation(user,session.csrf)));return;
   }
   if(req.path==='/portal'||req.path.startsWith('/api/portal/')){
    const data=internal(user)?[]:customerData(user,store);if(req.method!=='GET'){res.status(403).json({error:'ACTION_NOT_PERMITTED'});return;}
    if(req.path==='/api/portal/engagements'){res.json({engagements:data.map(summary)});return;}
    if(req.path.startsWith('/api/portal/engagements/')){const id=req.path.slice('/api/portal/engagements/'.length);const row=data.find(r=>r.engagementId===id);if(!row){res.sendStatus(404);return;}res.json(customerProjection(row));return;}
    if(req.path==='/api/portal/report'){
     const row=data.find(r=>r.engagementId===req.query.engagementId),report=row?.reports.find((p:any)=>p.reportId===req.query.reportId&&p.version===req.query.version);if(!report||!report.formats.pdf||![report.reportId,report.version].every(v=>/^[a-zA-Z0-9_.-]+$/.test(v))){res.sendStatus(404);return;}const target=path.resolve(process.env.HERMES_REPORTS_DIR||path.join(process.cwd(),'storage','reports'),`audit_report_${report.reportId}_${report.version}.pdf`);res.download(target);return;
    }
    if(req.path!=='/portal'){res.sendStatus(404);return;}
    res.type('html').send(page('My organization',`<div class="eyebrow">Customer workspace</div><h1>Your accounting work</h1><p>Only workspaces assigned to your organization appear here. Reports are AI-prepared drafts unless separately approved through the professional review process.</p>${data.length?data.map(r=>{const p=customerProjection(r);return `<section class="card"><h2>${e(r.clientName)}</h2><p>${e(r.period)} · ${e(r.status)}</p><h3>Documents</h3>${table(['Document','SHA-256'],p.documents.map((d:any)=>[d.filename,d.sha256]))}<h3>Supported accounting values</h3>${table(['Metric','Value','Period','Currency','Scale','Source'],p.facts.map((f:any)=>[f.label||f.metric,f.value,f.reportingPeriod||f.period,f.currency,f.scale||f.unit||'As recorded',f.sourceText]))}<h3>Shared findings</h3>${table(['Finding','Status'],p.findings.map((f:any)=>[f.title||f.message,f.status]))}<h3>Draft reports</h3>${p.reports.map((v:any)=>v.formats.includes('pdf')?`<p><a href="/api/portal/report?engagementId=${encodeURIComponent(r.engagementId)}&reportId=${encodeURIComponent(v.reportId)}&version=${encodeURIComponent(v.version)}">Download ${e(v.title)} — ${e(v.version)}</a></p>`:'').join('')}</section>`;}).join(''):'<section class="card"><h2>No organization work assigned yet</h2><p>Your administrator must explicitly assign your company workspace before any accounting data is visible.</p></section>'}`,navigation(user,session.csrf)));return;
   }
   // Default deny is deliberate: customers cannot reach any legacy/global endpoint,
   // including assets, reviewer APIs, raw evidence, infrastructure or write paths.
   if(!internal(user)){res.status(403).json({error:'TENANT_ROUTE_NOT_PERMITTED'});return;}
   if(!['GET','HEAD','OPTIONS'].includes(req.method))store.transaction(s=>store.event(s,user.id,'PRODUCT_ACTION',req.method+' '+req.path.slice(0,180)));
   (req as any).user={id:user.id,sessionId:session.hash,role:user.role,claims:['INTERNAL_OPERATOR'],isHuman:true};
   next();
  }catch(err:any){const known=/Invalid|Tenant|required|already|password|Account|Select|LOGIN_THROTTLED/.test(err.message);fail(res,err.message==='LOGIN_THROTTLED'?429:known?400:503,known?err.message:'Access service unavailable. Please try again.');}
 });
 return router;
}
