export const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const mark=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#10243b"/><path d="M19 17h28v7H27v5h17v7H27v5h20v7H19z" fill="#fff"/><circle cx="47" cy="17" r="5" fill="#29b6a6"/></svg>`;
export function page(title:string,content:string,nav='',publicPage=false){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="${publicPage?'index,follow':'noindex,nofollow'}"><meta name="description" content="Evidence-led AI-assisted bookkeeping, with clear human professional review boundaries."><meta property="og:title" content="${escape(title)} — Eve Bookkeeping"><meta property="og:description" content="Clear books. Traceable evidence. Human professional review."><meta property="og:type" content="website"><title>${escape(title)} — Eve Bookkeeping</title><link rel="icon" href="/brand/eve.svg" type="image/svg+xml"><style>
:root{--navy:#10243b;--accent:#137e76;--paper:#f4f7fa;--muted:#526378;font-family:Inter,system-ui,sans-serif;color:var(--navy);background:var(--paper)}*{box-sizing:border-box}body{margin:0}a{color:#126b68;text-underline-offset:3px}header,footer{padding:22px max(20px,calc((100vw - 1160px)/2));background:white;border-bottom:1px solid #dfe7ef}header{display:flex;align-items:center;justify-content:space-between;gap:22px;flex-wrap:wrap}.brand{display:flex;gap:10px;align-items:center;color:var(--navy);font-weight:800;text-decoration:none;font-size:20px}.brand img{width:38px;height:38px}nav{display:flex;gap:16px;flex-wrap:wrap;align-items:center}main{max-width:1160px;margin:auto;padding:36px 20px 64px}h1{font-size:clamp(32px,5vw,58px);line-height:1.1;letter-spacing:-.035em;max-width:850px}h2{font-size:24px}p{line-height:1.7;max-width:780px;color:var(--muted)}.lead{font-size:21px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.15em;font-weight:800;color:var(--accent)}.card{background:white;border:1px solid #dfe7ef;border-radius:18px;padding:26px;margin:20px 0;overflow-wrap:anywhere}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:18px}.grid .card{margin:0}.auth{max-width:480px;margin:35px auto}.auth h1{font-size:34px}label{display:block;margin:18px 0 7px;font-weight:650}input,select,textarea{width:100%;padding:13px;border:1px solid #9aabbc;border-radius:8px;font:inherit}input:focus,button:focus,a:focus{outline:3px solid #7cd6cd;outline-offset:3px}button,.button{display:inline-block;background:var(--navy);color:white;border:0;border-radius:9px;padding:13px 20px;font:inherit;font-weight:700;cursor:pointer;text-decoration:none;margin:12px 8px 12px 0}.secondary{background:#dff3ef;color:var(--navy)}small{line-height:1.6;color:var(--muted)}.notice{border-left:4px solid var(--accent);padding:12px 18px;background:#eaf5f2}.error{border-left:4px solid #b42318;padding:12px;background:#fff0ed;color:#942011}.scroll{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e2e8f0;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:var(--muted)}code,pre{overflow-wrap:anywhere;white-space:pre-wrap;font-size:12px}details{margin:12px 0}summary{cursor:pointer;font-weight:700}footer{font-size:13px;color:var(--muted)}.hero{padding:42px 0 54px}.stat{font-size:32px;font-weight:800}.inline{display:inline} .inline button{font-size:13px;padding:8px;margin:4px}@media(max-width:600px){header{padding:16px}main{padding:20px 16px 40px}.card{padding:20px}nav{gap:12px;font-size:14px}.hero{padding:20px 0}.auth{margin:12px auto}th,td{padding:9px}}
</style></head><body><header><a class="brand" href="/public"><img src="/brand/eve.svg" alt="">Eve Bookkeeping</a><nav>${nav||`<a href="/public/product">Product</a><a href="/public/security">Security & evidence</a><a href="${publicPage?'https://app.evesbookkeeping.com/login':'/login'}">Login</a>`}</nav></header><main>${content}</main><footer>Eve Bookkeeping · AI-assisted bookkeeping and accounting infrastructure.<br>AI-prepared work requires appropriate human professional review. Authentication does not grant CPA signoff authority.</footer></body></html>`;}
export const input=(name:string,label:string,type='text',extra='')=>`<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" ${extra}>`;
export const csrf=(token:string)=>`<input type="hidden" name="csrf" value="${escape(token)}">`;
export const table=(headers:string[],rows:unknown[][])=>`<div class="scroll"><table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${escape(c)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No records available.</td></tr>`}</tbody></table></div>`;
export const publicSections:Record<string,[string,string,string[]]>={
 home:['Clear books. Traceable evidence.','Bring documents, accounting evidence, financial statements and professional review into one connected workspace.',['Evidence accompanies every accounting conclusion.','AI prepares and checks; authorized professionals make approval decisions.','Your team can follow work from the original document to the rendered value.']],
 product:['A connected workspace for accounting work.','Eve connects intake, extraction, specialist processing, financial statements, evidence and AI-prepared review packages.',['Document intake and processing status','Financial statements with source lineage','Findings and draft review packages']],
 'how-it-works':['From document to reviewable work.','Upload a document, observe processing, inspect supported values, resolve findings and review the resulting draft.',['1. Bring your source documents.','2. Inspect extracted facts and accounting checks.','3. Review evidence and findings before professional approval.']],
 'cpa-firms':['More visibility for the reviewing professional.','Eve helps firms organize evidence and prepare work for review without treating an AI output as a licensed opinion.',['Keep source evidence close to workpapers.','Inspect specialist receipts and unresolved findings.','Retain explicit human approval boundaries.']],
 businesses:['Understand the work behind your numbers.','A customer workspace brings your company documents, financial statements and permitted reports together.',['A company-scoped view of accounting work.','Evidence behind financial values.','Clear distinction between drafts and approved professional work.']],
 security:['Evidence and access are part of the product.','Eve is being prepared for account-based, tenant-scoped access with durable sessions and traceable evidence.',['Access is checked at the server boundary.','Source hashes and lineage support inspection.','Professional approval is distinct from account access.']],
 academy:['Continuous quality through real product journeys.','Academy uses isolated synthetic exercises to operate the actual product UI and evaluate source-to-pixel truth.',['Desktop and mobile browser journeys','Evidence-based grading and persistent learning records','Customer work priority and a single Hermes scheduler']],
 about:['Accounting infrastructure built around evidence.','Eve Bookkeeping is an AI Creates AI initiative focused on useful, inspectable accounting assistance.',['AI-assisted bookkeeping','Evidence-led review','Human professional responsibility']],
 contact:['Let’s understand your accounting workflow.','Tell us about your business or firm, your source documents and the review process you need.',['Request a demo','Discuss business needs','Discuss a CPA firm workflow']]
};
export function marketing(slug:string){const section=publicSections[slug];if(!section)return null;const [title,description,items]=section;return page(title,`<section class="hero"><div class="eyebrow">Evidence-led accounting</div><h1>${title}</h1><p class="lead">${description}</p><a class="button" href="/public/contact">Request demo</a><a class="button secondary" href="https://app.evesbookkeeping.com/login">Login</a></section><div class="grid">${items.map((x,i)=>`<section class="card"><div class="eyebrow">0${i+1}</div><h2>${x}</h2><p>Keep the underlying evidence and review status visible as work moves forward.</p></section>`).join('')}</div>${slug==='contact'?'<section class="card"><h2>Start a conversation</h2><p><a href="mailto:sholom@aicreates.ai?subject=Eve%20Bookkeeping%20demo%20request">Email the Eve team</a>. Please do not include financial documents or sensitive account information in an initial demo request.</p></section>':''}<section class="card"><h2>Explore Eve</h2><nav>${Object.entries(publicSections).map(([k,v])=>`<a href="/public/${k}">${escape(k==='home'?'Home':k==='cpa-firms'?'For CPA firms':k==='businesses'?'For businesses':v[0])}</a>`).join('')}</nav><p>Get started by requesting access. Customer accounts are provisioned with an explicit organization assignment.</p><a class="button" href="/public/contact">Get started</a></section>`,undefined,true);}
