import { ProvenanceRecord } from '../factRegistry';
import { ExtractedFact } from '../../types';
import { ReportingEngine } from '../../../server/reportingEngine';

export interface ReportSection {
  id: string;
  title: string;
  content: string;
  citations: string[];
  tables?: Array<{
    title: string;
    headers: string[];
    rows: string[][];
  }>;
  chartData?: any;
}

export interface GeneratedDeliverableReport {
  id: string;
  title: string;
  companyName: string;
  projectName: string;
  deliverableType: string;
  audience: string;
  reportingPeriod: string;
  currency: string;
  brandColors: {
    primary: string;
    secondary: string;
    accent: string;
    bg: string;
  };
  validationPass: {
    passed: boolean;
    checksCount: number;
    warnings: string[];
  };
  sections: ReportSection[];
  publishedAt: string;
  signedOffBy?: string;
  factIdsUsed?: string[];
}

/**
 * Client-side compile helper. Production reports are generated by
 * ReportingEngine.generateFinancialReport via POST /api/deliverables/generate.
 * This engine refuses to invent line items when the fact store is empty.
 */
export class DeliverableWizardEngine {
  public generateReport(params: {
    companyName: string;
    projectName: string;
    projectId: string;
    workspaceId?: string;
    deliverableType: string;
    audience: string;
    detailLevel: string;
    brandColors?: { primary: string; secondary: string; accent: string; bg: string };
    facts?: ExtractedFact[] | ProvenanceRecord[];
    signedOffBy?: string;
  }): GeneratedDeliverableReport {
    const workspaceId = params.workspaceId || params.projectId;
    if (!workspaceId) {
      throw new Error("REFUSED: workspaceId is required to compile a report.");
    }

    const facts = (params.facts || []) as ExtractedFact[];
    if (!facts.length) {
      throw new Error("REFUSED: Zero validated facts in db.facts. Empty extraction cannot generate a report.");
    }

    const reportReady = facts.filter((f) => {
      try {
        const gate = ReportingEngine.evaluateFactEligibility(f as ExtractedFact);
        return gate.eligibilityStatus === "REPORT_READY";
      } catch {
        return false;
      }
    });

    if (reportReady.length === 0) {
      throw new Error("REFUSED: No REPORT_READY facts. Wizard will not export an unverified report.");
    }

    if (!params.signedOffBy || params.signedOffBy.toLowerCase().includes("sarah johnson")) {
      throw new Error("REFUSED: A real authenticated user must sign off. Fictitious auditors are not accepted.");
    }

    const brandColors = params.brandColors || { primary: '#003345', secondary: '#0066FF', accent: '#00A9E0', bg: '#F4F6F9' };
    const currency = reportReady[0]?.currencyOriginal || reportReady[0]?.currency || reportReady[0]?.functionalCurrency || '';

    const tableRows: string[][] = reportReady.map((f) => [
      f.labelNormalized || f.labelOriginal,
      f.valueOriginal || String(f.valueFunctional),
      f.status || 'pending_review',
      `Page ${f.pageNumber || '—'} (${f.documentId || 'source'})`
    ]);

    const citations = reportReady.map((f) =>
      `[${f.sourceDocument || f.documentId}, Page ${f.pageNumber}: ${f.labelNormalized} = ${f.valueOriginal}]`
    );

    const narrativeFacts = reportReady.filter((f) => f.sourceText && f.sourceText.length > 30);
    const narrativeContent = narrativeFacts.length > 0
      ? narrativeFacts.slice(0, 5).map((f) => `• **${f.labelNormalized} (${f.documentId}, Page ${f.pageNumber})**: ${f.sourceText}`).join('\n\n')
      : 'No narrative disclosures were extracted from source documents.';

    const sections: ReportSection[] = [
      {
        id: 'sec-exec-summary',
        title: '1. Executive Summary',
        content: `Compiled from ${reportReady.length} REPORT_READY fact(s) for ${params.companyName || 'the workspace'}. Audience: ${params.audience}. No figures were invented.`,
        citations: citations.slice(0, 2)
      },
      {
        id: 'sec-fin-highlights',
        title: '2. Source-Grounded Financial Highlights',
        content: `Line items below are copied from db.facts after eligibility gating.`,
        citations: citations.slice(0, 3),
        tables: [
          {
            title: `${params.companyName} statement summary`,
            headers: ['Financial Line Item', 'Reported Amount', 'Status', 'Source Citation'],
            rows: tableRows
          }
        ]
      },
      {
        id: 'sec-explanations-disclosures',
        title: '3. Source excerpts',
        content: narrativeContent,
        citations: citations.slice(0, 5)
      }
    ];

    return {
      id: `REP-${Date.now()}`,
      title: `${params.deliverableType} — ${params.companyName}`,
      companyName: params.companyName,
      projectName: params.projectName,
      deliverableType: params.deliverableType,
      audience: params.audience,
      reportingPeriod: reportReady[0]?.reportingPeriod || '',
      currency,
      brandColors,
      validationPass: {
        passed: true,
        checksCount: reportReady.length,
        warnings: []
      },
      sections,
      publishedAt: new Date().toISOString(),
      signedOffBy: params.signedOffBy,
      factIdsUsed: reportReady.map((f) => f.id)
    };
  }
}
