import React from 'react';
const money=(v:any,c:any)=>typeof v==='number'?`${c||'UNSPECIFIED'} ${v.toFixed(2)}`:'Not recorded';
const coord=(p:any)=>p?.sourceCoordinate?.sourceType==='SPREADSHEET'?`${p.sourceCoordinate.sheetName||'Sheet'}!${p.sourceCoordinate.cellAddress||p.sourceCoordinate.rangeAddress||'Not recorded'}`:p?.sourceCoordinate?.sourceType==='IMAGE'?`IMAGE page ${p.sourceCoordinate.pageNumber||1} · region ${p.sourceCoordinate.ocrRegionId||'Not recorded'}`:'Not recorded';
export const MixedSourceReconciliationPanel:React.FC<{review?:any}>=({review})=>{if(!review)return null;const sp=(review.parentEvidence||[]).find((p:any)=>p.sourceKind==='SPREADSHEET');const rc=(review.parentEvidence||[]).find((p:any)=>p.sourceKind==='RECEIPT_IMAGE');return <section className="border rounded-xl p-4 space-y-4" data-eve-mixed-source="true" data-eve-mixed-status={review.status} data-eve-mixed-promotion={review.promotionState}>
<div><h2 className="font-semibold">Mixed-source spreadsheet / receipt reconciliation</h2><p className="text-sm">Independent source families remain separately traceable. A structured spreadsheet does not override contradictory receipt evidence.</p></div>
<div className="grid md:grid-cols-2 gap-3 text-sm"><div className="border rounded-lg p-3"><strong>Spreadsheet evidence</strong><p>Value: {money(review.spreadsheetValue,review.currency)}</p><p>Source: {coord(sp)}</p><p className="break-all">SHA-256: {sp?.sourceSha256||'Not recorded'}</p><p className="break-all">Provenance: {sp?.provenanceId||'Not recorded'}</p></div><div className="border rounded-lg p-3"><strong>Receipt evidence</strong><p>Value: {money(review.receiptValue,review.currency)}</p><p>Source: {coord(rc)}</p><p className="break-all">SHA-256: {rc?.sourceSha256||'Not recorded'}</p><p className="break-all">Provenance: {rc?.provenanceId||'Not recorded'}</p></div></div>
<div className="border rounded-lg p-3 text-sm"><strong>Reconciliation decision</strong><p>Status: {review.status}</p><p>Difference: {money(review.difference,review.currency)}</p><p>Promotion state: {review.promotionState}</p><p>Action: {review.decision}</p><p>Canonical promoted value: {review.authoritativeValue===null||review.authoritativeValue===undefined?'NOT PROMOTED':money(review.authoritativeValue,review.currency)}</p><p>Source coverage: {review.sourceCoverageStatus}</p><p>Semantic alignment: {review.semanticStatus}</p></div>
{(review.warnings||[]).length>0&&<div className="border rounded-lg p-3 text-sm"><strong>Review warnings</strong>{review.warnings.map((w:string,i:number)=><p key={i}>{w}</p>)}</div>}
</section>};
