import React from 'react';
const money=(value:any,currency?:string)=>typeof value==='number'?`${currency||'UNSPECIFIED'} ${value.toFixed(2)}`:'Not recorded';
const loc=(c:any)=>c?.sheetName&&c?.cellAddress?`${c.sheetName}!${c.cellAddress}`:'Not recorded';
export const TrialBalanceReviewPanel:React.FC<{review?:any}>=({review})=>{if(!review)return null; const f=review.formulaReview||{}; return <section className="border rounded-xl p-4 space-y-4" data-eve-trial-balance="true" data-eve-trial-balance-status={review.status} data-eve-trial-balance-formula-integrity={review.formulaIntegrityStatus} data-eve-trial-balance-promotion={review.promotionState}>
  <div><h2 className="font-semibold">Trial balance reconciliation review</h2><p className="text-sm">Debit/credit equality is recomputed from account rows. Cached spreadsheet formula values cannot override an inconsistent underlying ledger, and this review is not financial-statement completeness or posting approval.</p></div>
  <div className="grid md:grid-cols-2 gap-3 text-sm"><div className="border rounded-lg p-3"><strong>Source</strong><p>Worksheet / range: {review.sheetName}!{review.sourceRange}</p><p>Account lines: {review.accountLineCount}</p><p>Hidden account rows included: {review.hiddenAccountLineCount}</p><p>Source coverage: {review.sourceCoverageStatus}</p><p>Semantic status: {review.semanticStatus}</p></div><div className="border rounded-lg p-3"><strong>Trial-balance arithmetic</strong><p>Total debits: {money(review.totalDebits,review.currency)}</p><p>Total credits: {money(review.totalCredits,review.currency)}</p><p>Variance: {money(review.variance,review.currency)}</p><p>Trial balance status: {review.status}</p><p>Formula integrity: {review.formulaIntegrityStatus}</p><p>Promotion state: {review.promotionState}</p></div></div>
  <div className="border rounded-lg p-3 text-sm"><strong>Total formulas</strong><p>Debit total: {loc(f.debitTotal?.sourceCoordinate)} · {f.debitTotal?.formula||'No formula'} · cached {f.debitTotal?.cachedValue ?? 'Not recorded'}</p><p>Credit total: {loc(f.creditTotal?.sourceCoordinate)} · {f.creditTotal?.formula||'No formula'} · cached {f.creditTotal?.cachedValue ?? 'Not recorded'}</p><p>Variance: {loc(f.variance?.sourceCoordinate)} · {f.variance?.formula||'No formula'} · cached {f.variance?.cachedValue ?? 'Not recorded'}</p></div>
  <div className="space-y-2 text-sm"><strong>Ledger rows</strong>{(review.lines||[]).map((line:any)=><article key={`${line.rowNumber}-${line.accountCode}`} className="border rounded-lg p-3"><p>{line.accountCode} · {line.accountName} · row {line.rowNumber} · hidden {line.hiddenRow?'YES':'NO'}</p><p>Debit {money(line.debit,review.currency)} · Credit {money(line.credit,review.currency)}</p><p>Debit source: {loc(line.debitCoordinate)} · Credit source: {loc(line.creditCoordinate)}</p><p>Evidence: {[line.accountEvidenceRef,line.debitEvidenceRef,line.creditEvidenceRef].filter(Boolean).join(', ')||'Not recorded'}</p></article>)}</div>
  <p className="text-xs break-all">Source SHA-256: {review.sourceSha256||'Not recorded'}</p>
</section>;};
