from pathlib import Path

p = Path('server/cpaOrganization/taskEvidenceSufficiencyEngine.ts')
text = p.read_text()
old = """    const gapAssessments: GapTaskAssessment[] = gaps.map(gap => {\n      const affectedConclusions = task.conclusions.filter(c => intersects(gap.affectedCapabilities || [], c.requiredCapabilities || []));\n      const derived = deriveMateriality(gap, affectedConclusions);\n      return {\n        gapId: gap.gapId,\n        derivedMateriality: derived.materiality,\n        affectsCurrentTask: affectedConclusions.length > 0,\n        affectedConclusionIds: affectedConclusions.map(c => c.conclusionId),\n        rationale: derived.rationale,\n      };\n    });\n"""
new = """    const gapAssessments: GapTaskAssessment[] = gaps.map(gap => {\n      // Unknown impact scope is fail-safe: until Eve can identify what a known gap affects,\n      // it must be evaluated against every current conclusion rather than silently treated as unrelated.\n      const unknownImpactScope = !Array.isArray(gap.affectedCapabilities) || gap.affectedCapabilities.length === 0;\n      const affectedConclusions = unknownImpactScope\n        ? task.conclusions\n        : task.conclusions.filter(c => intersects(gap.affectedCapabilities, c.requiredCapabilities || []));\n      const derived = deriveMateriality(gap, affectedConclusions);\n      const rationale = unknownImpactScope && derived.materiality === 'UNKNOWN'\n        ? ['Gap impact scope is not established; fail-safe evaluation applies it to all current conclusions.', ...derived.rationale]\n        : derived.rationale;\n      return {\n        gapId: gap.gapId,\n        derivedMateriality: derived.materiality,\n        affectsCurrentTask: affectedConclusions.length > 0,\n        affectedConclusionIds: affectedConclusions.map(c => c.conclusionId),\n        rationale,\n      };\n    });\n"""
if old not in text:
    raise SystemExit('P1_009_PATCH_TARGET_NOT_FOUND')
p.write_text(text.replace(old, new, 1))
print('P1_009_PATCH_APPLIED=YES')
