import { validateSourceCoordinate } from '../../src/lib/evidence/universalSourceEvidence.js';
import type { FiveDimensionCheck } from './academyMinervaLab.js';

export type ClientIsolationBindingKind='DOCUMENT'|'PROVENANCE'|'FACT'|'FINDING'|'CLARIFICATION'|'RENDERED_VALUE';
export interface ClientIsolationScope{clientId:string;clientName:string;workspaceId:string;engagementId:string;}
export interface ClientIsolationBinding{kind:ClientIsolationBindingKind;id:string;clientId:string;clientName:string;workspaceId:string;engagementId:string;sourceDocumentId?:string;factId?:string;provenanceId?:string;sourceSha256?:string;sourceArtifactId?:string;sourceCoordinate?:any;originalName?:string;label?:string;period?:string;value?:number;state?:string;sourceText?:string;}
export interface ClientIsolationBindingResult extends ClientIsolationBinding{issues:string[];}
export interface ClientIsolationReview{reviewId:string;status:'VERIFIED_CLIENT_ISOLATION'|'BLOCKED_CLIENT_IDENTITY_MISMATCH';promotionState:'READY_FOR_AUTHORIZED_REVIEW'|'BLOCKED_CLIENT_ISOLATION';decision:'PRESERVE_CLIENT_SCOPED_EVIDENCE'|'REQUEST_CLIENT_SCOPE_REPAIR';scopeCount:number;bindingCount:number;invalidBindingCount:number;crossClientLeakCount:number;canonicalBatchValue:null;collisionSummary:{sharedFilenames:string[];sharedValues:number[];sharedLabels:string[];sharedPeriods:string[]};clientSummaries:Array<ClientIsolationScope&{documents:number;provenance:number;facts:number;findings:number;clarifications:number;renderedValues:number}>;bindingResults:ClientIsolationBindingResult[];evidenceRefs:string[];issues:string[];}
const key=(x:{clientId:string;workspaceId:string;engagementId:string})=>`${x.clientId}|${x.workspaceId}|${x.engagementId}`;
const shared=(pairs:Array<[string,string]>)=>{const by=new Map<string,Set<string>>();for(const [v,c] of pairs){if(!v)continue;const s=by.get(v)||new Set<string>();s.add(c);by.set(v,s);}return [...by.entries()].filter(([,s])=>s.size>1).map(([v])=>v).sort();};
export function evaluateBulkClientIsolation(params:{scopes:ClientIsolationScope[];bindings:ClientIsolationBinding[];reviewId?:string}):ClientIsolationReview{
 const scopes=Array.isArray(params.scopes)?params.scopes:[],bindings=Array.isArray(params.bindings)?params.bindings:[];const scopeByClient=new Map(scopes.map(s=>[s.clientId,s]));const docs=new Map(bindings.filter(b=>b.kind==='DOCUMENT').map(b=>[b.id,b]));const facts=new Map(bindings.filter(b=>b.kind==='FACT').map(b=>[b.id,b]));const provs=new Map(bindings.filter(b=>b.kind==='PROVENANCE').map(b=>[b.id,b]));
 const results:ClientIsolationBindingResult[]=bindings.map(b=>{const issues:string[]=[];const s=scopeByClient.get(b.clientId);if(!s)issues.push('UNKNOWN_CLIENT_SCOPE');else{if(b.clientName!==s.clientName)issues.push(`CLIENT_NAME_MISMATCH:${b.clientName}`);if(b.workspaceId!==s.workspaceId)issues.push(`WORKSPACE_MISMATCH:${b.workspaceId}`);if(b.engagementId!==s.engagementId)issues.push(`ENGAGEMENT_MISMATCH:${b.engagementId}`);}
  if(b.sourceDocumentId){const d=docs.get(b.sourceDocumentId);if(!d)issues.push(`MISSING_DOCUMENT_REFERENCE:${b.sourceDocumentId}`);else if(key(d)!==key(b))issues.push(`CROSS_CLIENT_DOCUMENT_REFERENCE:${b.sourceDocumentId}`);}
  if(b.factId){const f=facts.get(b.factId);if(!f)issues.push(`MISSING_FACT_REFERENCE:${b.factId}`);else if(key(f)!==key(b))issues.push(`CROSS_CLIENT_FACT_REFERENCE:${b.factId}`);else if(b.kind==='RENDERED_VALUE'&&Number.isFinite(Number(b.value))&&Number.isFinite(Number(f.value))&&Math.abs(Number(b.value)-Number(f.value))>0.005)issues.push(`RENDERED_VALUE_MISMATCH:${b.factId}`);}
  if(b.provenanceId&&b.kind!=='PROVENANCE'){const p=provs.get(b.provenanceId);if(!p)issues.push(`MISSING_PROVENANCE_REFERENCE:${b.provenanceId}`);else if(key(p)!==key(b))issues.push(`CROSS_CLIENT_PROVENANCE_REFERENCE:${b.provenanceId}`);}
  if(b.kind==='PROVENANCE'){if(!b.sourceCoordinate)issues.push('MISSING_SOURCE_COORDINATE');else{for(const issue of validateSourceCoordinate(b.sourceCoordinate).issues)issues.push(`COORDINATE_INVALID:${issue}`);if(b.sourceSha256&&b.sourceCoordinate.sourceSha256!==b.sourceSha256)issues.push('SOURCE_SHA_DOES_NOT_MATCH_COORDINATE_SHA');if(b.sourceArtifactId&&b.sourceCoordinate.sourceArtifactId!==b.sourceArtifactId)issues.push('SOURCE_ARTIFACT_DOES_NOT_MATCH_COORDINATE_ARTIFACT');}const d=b.sourceDocumentId?docs.get(b.sourceDocumentId):undefined;if(d&&b.sourceSha256&&d.sourceSha256!==b.sourceSha256)issues.push('PROVENANCE_SHA_DOES_NOT_MATCH_DOCUMENT_SHA');}
  if(b.kind==='FACT'){const d=b.sourceDocumentId?docs.get(b.sourceDocumentId):undefined;const p=b.provenanceId?provs.get(b.provenanceId):undefined;if(d&&b.sourceSha256&&d.sourceSha256!==b.sourceSha256)issues.push('FACT_SHA_DOES_NOT_MATCH_DOCUMENT_SHA');if(p&&b.sourceSha256&&p.sourceSha256!==b.sourceSha256)issues.push('FACT_SHA_DOES_NOT_MATCH_PROVENANCE_SHA');}
  return {...b,issues};});
 const issues=results.flatMap(r=>r.issues.map(i=>`${r.kind}:${r.id}:${i}`));const crossClientLeakCount=issues.filter(i=>i.includes('CROSS_CLIENT_')||i.includes('WORKSPACE_MISMATCH')||i.includes('ENGAGEMENT_MISMATCH')||i.includes('CLIENT_NAME_MISMATCH')).length;const invalidBindingCount=results.filter(r=>r.issues.length>0).length;const status=invalidBindingCount?'BLOCKED_CLIENT_IDENTITY_MISMATCH':'VERIFIED_CLIENT_ISOLATION';
 const clientSummaries=scopes.map(s=>{const own=bindings.filter(b=>b.clientId===s.clientId);return {...s,documents:own.filter(b=>b.kind==='DOCUMENT').length,provenance:own.filter(b=>b.kind==='PROVENANCE').length,facts:own.filter(b=>b.kind==='FACT').length,findings:own.filter(b=>b.kind==='FINDING').length,clarifications:own.filter(b=>b.kind==='CLARIFICATION').length,renderedValues:own.filter(b=>b.kind==='RENDERED_VALUE').length};});
 const sharedValues=shared(bindings.filter(b=>b.kind==='FACT'&&Number.isFinite(Number(b.value))).map(b=>[Number(b.value).toFixed(2),b.clientId] as [string,string])).map(Number);const collisionSummary={sharedFilenames:shared(bindings.filter(b=>b.kind==='DOCUMENT').map(b=>[String(b.originalName||''),b.clientId])),sharedValues,sharedLabels:shared(bindings.filter(b=>b.kind==='FACT').map(b=>[String(b.label||''),b.clientId])),sharedPeriods:shared(bindings.filter(b=>b.kind==='FACT').map(b=>[String(b.period||''),b.clientId]))};
 const evidenceRefs=[...new Set(bindings.flatMap(b=>[`binding:${b.kind}:${b.id}`,b.sourceSha256?`source:${b.sourceSha256}`:'',b.provenanceId?`provenance:${b.provenanceId}`:''].filter(Boolean)))];
 return {reviewId:params.reviewId||'bulk-client-isolation-review',status,promotionState:status==='VERIFIED_CLIENT_ISOLATION'?'READY_FOR_AUTHORIZED_REVIEW':'BLOCKED_CLIENT_ISOLATION',decision:status==='VERIFIED_CLIENT_ISOLATION'?'PRESERVE_CLIENT_SCOPED_EVIDENCE':'REQUEST_CLIENT_SCOPE_REPAIR',scopeCount:scopes.length,bindingCount:bindings.length,invalidBindingCount,crossClientLeakCount,canonicalBatchValue:null,collisionSummary,clientSummaries,bindingResults:results,evidenceRefs,issues};
}
const pass=(checkId:string,label:string,evidenceRefs:string[],details:string[]):FiveDimensionCheck=>({checkId,label,outcome:'PASS',evidenceRefs,details});
export function buildClientIsolationFiveDimensionChecks(clean:ClientIsolationReview,tampered:ClientIsolationReview){return {source:[pass('client-isolation-source-tuples','Every document and provenance coordinate remains bound to its client workspace and engagement tuple',clean.evidenceRefs,[`scopes=${clean.scopeCount}; bindings=${clean.bindingCount}; invalid=${clean.invalidBindingCount}`]),pass('client-isolation-tamper-blocks','Cross-client document fact and provenance references fail closed',tampered.evidenceRefs,[`status=${tampered.status}; leaks=${tampered.crossClientLeakCount}; issues=${tampered.issues.join(' | ')}`])],semantic:[pass('client-isolation-collisions-do-not-merge','Matching filenames values labels and periods remain separate because client identity is authoritative',clean.evidenceRefs,[`filenames=${clean.collisionSummary.sharedFilenames.join(',')}; values=${clean.collisionSummary.sharedValues.join(',')}; labels=${clean.collisionSummary.sharedLabels.join(',')}; periods=${clean.collisionSummary.sharedPeriods.join(',')}`]),pass('client-isolation-pbc-findings-scoped','Findings and clarification references remain within the same client tuple',clean.evidenceRefs,clean.clientSummaries.map(s=>`${s.clientName}: findings=${s.findings}; clarifications=${s.clarifications}`))],accounting:[pass('client-isolation-rendered-values-scoped','Identical accounting values remain separately rendered and fact-bound per client without batch aggregation',clean.evidenceRefs,[`canonicalBatchValue=${clean.canonicalBatchValue}; rendered=${clean.clientSummaries.map(s=>`${s.clientId}:${s.renderedValues}`).join(',')}`]),pass('client-isolation-cross-client-blocks','A cross-client reference blocks promotion instead of borrowing corroboration or accounting truth',tampered.evidenceRefs,[`promotion=${tampered.promotionState}; decision=${tampered.decision}`])]};}
