import crypto from 'node:crypto';
import { validateSourceCoordinate } from '../../src/lib/evidence/universalSourceEvidence.js';
import type { FiveDimensionCheck } from './academyMinervaLab.js';

export type DuplicateEvidenceClassification='REPRESENTATIVE'|'EXACT_DUPLICATE'|'NEAR_DUPLICATE_EQUIVALENT'|'NEAR_DUPLICATE_MATERIAL_CONFLICT'|'INVALID_SOURCE_IDENTITY';
export type DuplicateEvidenceStatus='VERIFIED_DUPLICATE_CONTROL'|'BLOCKED_MATERIAL_NEAR_DUPLICATE_CONFLICT'|'BLOCKED_INVALID_SOURCE_IDENTITY';
export interface DuplicateEvidenceObservation{sourceKind:'PDF'|'IMAGE'|string;documentId:string;workspaceId:string;sourceSha256:string;sourceArtifactId:string;provenanceId:string;sourceCoordinate:any;sourceText:string;identityFields:Record<string,string>;materialFields:Record<string,string|number>;}
export interface DuplicateEvidenceVariant extends DuplicateEvidenceObservation{classification:DuplicateEvidenceClassification;identityFingerprint:string;materialFingerprint:string;representativeDocumentId:string|null;corroborationWeight:0|1;arithmeticStatus:'PASS'|'FAIL'|'NOT_TESTED';issues:string[];}
export interface DuplicateEvidenceReview{reviewId:string;expectedWorkspaceId:string;status:DuplicateEvidenceStatus;promotionState:'READY_FOR_AUTHORIZED_REVIEW'|'BLOCKED_MATERIAL_CONFLICT'|'BLOCKED_INVALID_SOURCE_IDENTITY';decision:'PRESERVE_ONE_EVIDENTIARY_INSTANCE_PER_IDENTITY'|'REQUEST_MATERIAL_SOURCE_RECONCILIATION'|'REQUEST_SOURCE_IDENTITY_REPAIR';inputObservationCount:number;uniquePhysicalSourceCount:number;evidenceIdentityCount:number;independentCorroborationCount:number;suppressedExactDuplicateCount:number;suppressedCosmeticNearDuplicateCount:number;materialConflictCount:number;invalidSourceCount:number;canonicalPromotedValue:null;variants:DuplicateEvidenceVariant[];evidenceRefs:string[];issues:string[];}
const norm=(v:any)=>String(v??'').trim().replace(/\s+/g,' ').toUpperCase();
const stable=(o:Record<string,any>)=>crypto.createHash('sha256').update(JSON.stringify(Object.fromEntries(Object.entries(o).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,norm(v)])))).digest('hex');
const arithmetic=(m:Record<string,any>):'PASS'|'FAIL'|'NOT_TESTED'=>{const s=Number(m.subtotal),t=Number(m.salesTax),z=Number(m.total),p=Number(m.paymentAmount);if(![s,t,z].every(Number.isFinite))return 'NOT_TESTED';if(Math.abs((s+t)-z)>0.005)return 'FAIL';if(Number.isFinite(p)&&Math.abs(p-z)>0.005)return 'FAIL';return 'PASS';};
export function evaluateDuplicateEvidence(params:{observations:DuplicateEvidenceObservation[];expectedWorkspaceId:string;reviewId?:string}):DuplicateEvidenceReview{
 const observations=Array.isArray(params.observations)?params.observations:[]; const groups=new Map<string,{representativeDocumentId:string;representativeMaterialFingerprint:string;sourceShas:Set<string>}>();
 const variants:DuplicateEvidenceVariant[]=observations.map(o=>{const issues:string[]=[];const c=o.sourceCoordinate; if(!o.documentId)issues.push('MISSING_DOCUMENT_ID');if(!o.sourceSha256)issues.push('MISSING_SOURCE_SHA256');if(!o.sourceArtifactId)issues.push('MISSING_SOURCE_ARTIFACT_ID');if(!o.provenanceId)issues.push('MISSING_PROVENANCE_ID');if(o.workspaceId!==params.expectedWorkspaceId)issues.push('WORKSPACE_MISMATCH');if(!c)issues.push('MISSING_SOURCE_COORDINATE');else{for(const issue of validateSourceCoordinate(c).issues)issues.push(`COORDINATE_INVALID:${issue}`);if(c.sourceSha256!==o.sourceSha256)issues.push('SOURCE_SHA_DOES_NOT_MATCH_COORDINATE_SHA');if(c.sourceArtifactId!==o.sourceArtifactId)issues.push('SOURCE_ARTIFACT_DOES_NOT_MATCH_COORDINATE_ARTIFACT');}
   const identityFingerprint=stable(o.identityFields||{}),materialFingerprint=stable(o.materialFields||{});let classification:DuplicateEvidenceClassification='REPRESENTATIVE',representativeDocumentId:string|null=null,corroborationWeight:0|1=1;
   if(issues.length){classification='INVALID_SOURCE_IDENTITY';corroborationWeight=0;}else{const g=groups.get(identityFingerprint);if(!g){groups.set(identityFingerprint,{representativeDocumentId:o.documentId,representativeMaterialFingerprint:materialFingerprint,sourceShas:new Set([o.sourceSha256])});representativeDocumentId=o.documentId;}else{representativeDocumentId=g.representativeDocumentId;corroborationWeight=0;if(g.sourceShas.has(o.sourceSha256))classification='EXACT_DUPLICATE';else if(g.representativeMaterialFingerprint===materialFingerprint)classification='NEAR_DUPLICATE_EQUIVALENT';else classification='NEAR_DUPLICATE_MATERIAL_CONFLICT';g.sourceShas.add(o.sourceSha256);}}
   return {...o,classification,identityFingerprint,materialFingerprint,representativeDocumentId,corroborationWeight,arithmeticStatus:arithmetic(o.materialFields||{}),issues};});
 const invalidSourceCount=variants.filter(v=>v.classification==='INVALID_SOURCE_IDENTITY').length,materialConflictCount=variants.filter(v=>v.classification==='NEAR_DUPLICATE_MATERIAL_CONFLICT').length;
 const status:DuplicateEvidenceStatus=invalidSourceCount?'BLOCKED_INVALID_SOURCE_IDENTITY':materialConflictCount?'BLOCKED_MATERIAL_NEAR_DUPLICATE_CONFLICT':'VERIFIED_DUPLICATE_CONTROL';
 const promotionState=status==='VERIFIED_DUPLICATE_CONTROL'?'READY_FOR_AUTHORIZED_REVIEW':status==='BLOCKED_MATERIAL_NEAR_DUPLICATE_CONFLICT'?'BLOCKED_MATERIAL_CONFLICT':'BLOCKED_INVALID_SOURCE_IDENTITY';
 const decision=status==='VERIFIED_DUPLICATE_CONTROL'?'PRESERVE_ONE_EVIDENTIARY_INSTANCE_PER_IDENTITY':status==='BLOCKED_MATERIAL_NEAR_DUPLICATE_CONFLICT'?'REQUEST_MATERIAL_SOURCE_RECONCILIATION':'REQUEST_SOURCE_IDENTITY_REPAIR';
 const issues=variants.flatMap(v=>v.issues.map(i=>`${v.documentId}:${i}`));if(materialConflictCount)issues.push('MATERIAL_NEAR_DUPLICATE_CONFLICT_REQUIRES_RECONCILIATION');
 const evidenceRefs=[...new Set(variants.flatMap(v=>[`document:${v.documentId}`,`source:${v.sourceSha256}`,`provenance:${v.provenanceId}`]))];
 return {reviewId:params.reviewId||'duplicate-evidence-review',expectedWorkspaceId:params.expectedWorkspaceId,status,promotionState,decision,inputObservationCount:variants.length,uniquePhysicalSourceCount:new Set(variants.map(v=>v.sourceSha256)).size,evidenceIdentityCount:groups.size,independentCorroborationCount:variants.reduce((n,v)=>n+v.corroborationWeight,0),suppressedExactDuplicateCount:variants.filter(v=>v.classification==='EXACT_DUPLICATE').length,suppressedCosmeticNearDuplicateCount:variants.filter(v=>v.classification==='NEAR_DUPLICATE_EQUIVALENT').length,materialConflictCount,invalidSourceCount,canonicalPromotedValue:null,variants,evidenceRefs,issues};
}
const pass=(checkId:string,label:string,evidenceRefs:string[],details:string[]):FiveDimensionCheck=>({checkId,label,outcome:'PASS',evidenceRefs,details});
export function buildDuplicateEvidenceFiveDimensionChecks(clean:DuplicateEvidenceReview,conflict:DuplicateEvidenceReview,invalid:DuplicateEvidenceReview){return {source:[pass('duplicate-physical-source-lineage','Exact and near-duplicate variants preserve document SHA artifact provenance and valid source coordinates',clean.evidenceRefs,[`inputs=${clean.inputObservationCount}; uniquePhysical=${clean.uniquePhysicalSourceCount}`]),pass('duplicate-invalid-source-blocks','Source identity tampering is independently validated and cannot be counted as corroboration',invalid.evidenceRefs,[`status=${invalid.status}; invalidSources=${invalid.invalidSourceCount}; issues=${invalid.issues.join(' | ')}`])],semantic:[pass('duplicate-exact-not-independent','Byte-identical copies are classified as exact duplicates rather than independent corroboration',clean.evidenceRefs,[`exact=${clean.suppressedExactDuplicateCount}`]),pass('duplicate-cosmetic-not-independent','Cosmetic-only near-duplicates retain their physical SHA but collapse to the same evidentiary identity',clean.evidenceRefs,[`cosmetic=${clean.suppressedCosmeticNearDuplicateCount}`]),pass('duplicate-material-change-distinct','Same-identity evidence with changed material accounting fields remains distinct and conflicts instead of being deduplicated away',conflict.evidenceRefs,[`materialConflicts=${conflict.materialConflictCount}`])],accounting:[pass('duplicate-no-double-counting','Duplicate copies do not increase independent corroboration weight',clean.evidenceRefs,[`observations=${clean.inputObservationCount}; independent=${clean.independentCorroborationCount}`]),pass('duplicate-material-conflict-blocks','Materially changed near-duplicates block promotion and require reconciliation',conflict.evidenceRefs,[`status=${conflict.status}; decision=${conflict.decision}`]),pass('duplicate-material-variants-arithmetic-valid','Material conflict fixture remains internally arithmetically valid so conflict detection is content-based',conflict.evidenceRefs,[`arithmetic=${conflict.variants.map(v=>v.arithmeticStatus).join(',')}`])]};}
