import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { IdentityStore,hashPassword,verifyPassword,digest } from '../access/identityStore.js';
import { createAccessPortal } from '../access/accessPortal.js';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'eve-access-test-'));const original=process.cwd();process.chdir(temp);fs.mkdirSync('storage');
fs.mkdirSync(path.join('dist','brand','product'),{recursive:true});fs.writeFileSync(path.join('dist','brand','product','eve-product-overview.jpg'),'synthetic-capture');
fs.writeFileSync('storage/ai_cpa_storage.json',JSON.stringify({workspaces:[{id:'customer-a',name:'A',classification:'CUSTOMER'},{id:'customer-b',name:'B',classification:'CUSTOMER'},{id:'academy',name:'Academy',classification:'ACADEMY'}],documents:[],facts:[],findings:[],reports:[]}));
const baseline=fs.readFileSync('storage/ai_cpa_storage.json');
const store=new IdentityStore(path.join(temp,'identity'));
const bootstrap=store.invite('owner@example.test','OWNER',null,'test',true);
assert(!fs.readFileSync(store.file,'utf8').includes(bootstrap.temporaryPassword));assert(verifyPassword(bootstrap.temporaryPassword,store.read().users[0].passwordHash));
const first=store.login('owner@example.test',bootstrap.temporaryPassword,'ip')!;assert(first.session.restricted);assert.equal(store.login('owner@example.test',bootstrap.temporaryPassword,'ip'),null);
const reopened=new IdentityStore(store.root);assert(reopened.session(first.token));
store.changePassword(first.token,'a long permanent test password','');assert.equal(store.session(first.token),null);assert.equal(store.login('owner@example.test',bootstrap.temporaryPassword,'ip'),null);
const owner=store.login('owner@example.test','a long permanent test password','ip')!;assert(!owner.session.restricted);
store.transaction(s=>s.tenants.push({id:'tenant-a',name:'A',workspaceIds:['customer-a']},{id:'tenant-b',name:'B',workspaceIds:['customer-b']}));
const invite=store.invite('client@example.test','CLIENT_ADMIN','tenant-a','owner');const start=store.login('client@example.test',invite.temporaryPassword,'client')!;store.changePassword(start.token,'a different permanent test password','');const client=store.login('client@example.test','a different permanent test password','client')!;
const app=express();app.use(createAccessPortal(store));app.use((req,res)=>res.json({legacy:true,user:(req as any).user||null,customerUpload:(req as any).eveCustomerUpload||null,path:req.path}));
const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const port=(server.address() as any).port;
const request=(url:string,token?:string,options:any={})=>fetch(`http://127.0.0.1:${port}${url}`,{redirect:'manual',...options,headers:{host:'eve.test',...(token?{cookie:`__Host-eve_session=${token}`} :{}),...options.headers}});
try{
 process.env.EVE_PUBLIC_PREVIEW_HOSTS='eve.test,127.0.0.1';
 const publicHome=await request('/');assert.equal(publicHome.status,200);const publicHtml=await publicHome.text();assert.match(publicHtml,/<title>Eve Bookkeeping \| Evidence-Led Bookkeeping Intelligence<\/title>/);assert.match(publicHtml,/name="twitter:title" content="Eve Bookkeeping \| Evidence-Led Bookkeeping Intelligence"/);assert.match(publicHtml,/name="twitter:image" content="https:\/\/evesbookkeeping.com\/brand\/og-home.png"/);assert.match(publicHome.headers.get('content-security-policy')||'',/frame-ancestors 'none'/);
 process.env.EVE_PUBLIC_CANONICAL_ORIGIN='https://eve-candidate.example.test/';const candidateHome=await request('/');const candidateHtml=await candidateHome.text();assert.match(candidateHtml,/property="og:url" content="https:\/\/eve-candidate.example.test"/);assert.match(candidateHtml,/property="og:image" content="https:\/\/eve-candidate.example.test\/brand\/og-home.png"/);delete process.env.EVE_PUBLIC_CANONICAL_ORIGIN;
 assert.equal((await request('/product')).status,200);
 assert.equal((await request('/brand/product/eve-product-overview.jpg')).status,200);
 assert.equal((await request('/brand/product/../../storage/ai_cpa_storage.json')).status,404);
 assert.equal((await request('/robots.txt')).status,200);
 assert.equal((await request('/sitemap.xml')).status,200);
 assert.equal((await request('/not-a-page')).status,404);
 delete process.env.EVE_PUBLIC_PREVIEW_HOSTS;
 assert.equal((await request('/owner')).status,302);
 assert.equal((await request('/api/portal/engagements')).status,401);
 assert.equal((await request('/owner',first.token)).status,302);
 for(const url of ['/owner','/owner/university','/owner/users','/api/workspaces','/api/review/facts','/api/cpa/engagements/universal','/api/queue/jobs','/api/health','/storage/accounts.json','/operator-login'])assert.equal((await request(url,client.token)).status,403,url);
 const response=await request('/api/portal/engagements',client.token);const data=await response.json();assert.deepEqual(data.engagements.map((r:any)=>r.workspaceId),['customer-a']);
 assert.equal((await request('/api/portal/engagements/customer-b',client.token)).status,404);
 assert.equal((await request('/api/portal/engagements/academy',client.token)).status,404);
 assert.equal((await request('/api/portal/report?engagementId=customer-b&reportId=x&version=x',client.token)).status,404);
 assert.equal((await request('/api/portal/engagements/customer-a',client.token)).status,200);
 assert.equal((await request('/portal',client.token)).status,200);
 assert.equal((await request('/api/documents/upload',client.token,{method:'POST',headers:{origin:`https://127.0.0.1:${port}`,'x-eve-csrf':client.session.csrf}})).status,403);
 const portalIntake=await request('/api/portal/intake',client.token,{method:'POST',headers:{origin:`https://127.0.0.1:${port}`,'x-eve-csrf':client.session.csrf}});assert.equal(portalIntake.status,200);const portalBridge=await portalIntake.json();assert.equal(portalBridge.path,'/api/documents/upload');assert.deepEqual(portalBridge.customerUpload.workspaceIds,['customer-a']);
 const multipartIntake=await request('/api/portal/intake',undefined,{method:'POST',headers:{origin:`https://127.0.0.1:${port}`,cookie:`__Host-eve_session=${client.token}; __Host-eve_csrf=${client.session.csrf}`,'content-type':'multipart/form-data; boundary=eve-test-boundary'},body:'--eve-test-boundary--\r\n'});assert.equal(multipartIntake.status,200);const multipartBridge=await multipartIntake.json();assert.equal(multipartBridge.path,'/api/documents/upload');assert.deepEqual(multipartBridge.customerUpload.workspaceIds,['customer-a']);
 assert.equal((await request('/owner',owner.token)).status,200);
 const university=await request('/owner/university',owner.token);assert.equal(university.status,200);const universityHtml=await university.text();for(const label of ['University Overview','Live Examinations','Synthetic Customers','Raw Input Lab','Capability Matrix','Failures &amp; Remediation','Regression','Minerva','Workforce','Hermes','Learning / Darwin','Curriculum','Owner Requests'])assert.match(universityHtml,new RegExp(label));
 assert.equal((await request('/api/workspaces',owner.token)).status,200);
 const principal=(await(await request('/api/cpa/any',owner.token)).json()).user;assert.equal(principal.role,'OWNER');assert.deepEqual(principal.claims,['INTERNAL_OPERATOR']);
 assert.equal((await request('/auth/revoke-all',owner.token,{method:'POST'})).status,403);
 assert.equal((await request('/auth/revoke-all',owner.token,{method:'POST',headers:{origin:'https://evil.test','x-eve-csrf':owner.session.csrf}})).status,403);
 const reset=store.reset(client.user.id,owner.user.id);assert.equal(store.session(client.token),null);const restricted=store.login('client@example.test',reset,'reset')!;
 assert.equal((await request('/portal',restricted.token)).headers.get('location'),'/account/password');assert.equal((await request('/api/portal/engagements',restricted.token)).status,403);assert.equal((await request('/account/password',restricted.token)).status,200);
 assert.equal(store.login('client@example.test',reset,'reset'),null);
 // Native same-origin form POSTs need a non-opaque Origin. no-referrer
 // makes Chromium send Origin: null, rejecting valid forms before authentication.
 const login=await request('/login');assert.equal(login.headers.get('referrer-policy'),'same-origin');const pre=login.headers.get('set-cookie')!.split(';')[0];const html=await login.text();const csrf=html.match(/name="csrf" value="([^"]+)"/)![1];assert.match(pre,/__Host-eve_login_csrf/);
 for(const origin of ['null','https://evil.test']){const rejected=await request('/auth/login',undefined,{method:'POST',headers:{origin,cookie:pre,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({email:'owner@example.test',password:'a long permanent test password',csrf}).toString()});assert.equal(rejected.status,403);}
 const real=await request('/auth/login',undefined,{method:'POST',headers:{origin:`https://127.0.0.1:${port}`,cookie:pre,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({email:'owner@example.test',password:'a long permanent test password',csrf}).toString()});assert.equal(real.status,303);assert.match(real.headers.get('set-cookie')!,/Secure; HttpOnly; SameSite=Strict/);assert.match(real.headers.get('set-cookie')!,/__Host-eve_csrf=.*Secure; SameSite=Strict/);
 const loginCookie=real.headers.get('set-cookie')!.split(';')[0].split('=')[1];assert(store.session(loginCookie));
 const result=await request('/auth/revoke-all',owner.token,{method:'POST',headers:{origin:`https://127.0.0.1:${port}`,'x-eve-csrf':owner.session.csrf}});assert.equal(result.status,303);assert.equal(store.session(loginCookie),null);assert.equal(store.session(owner.token),null);
 for(let i=0;i<10;i++)store.login('none@example.test','not a valid password','throttle');assert.throws(()=>store.login('none@example.test','not a valid password','throttle'),/THROTTLED/);
 assert.deepEqual(fs.readFileSync('storage/ai_cpa_storage.json'),baseline);
 assert(!fs.readFileSync(store.file,'utf8').includes('a long permanent test password'));
 console.log('PASS: durable one-time setup, password replacement, session revocation, HTTP cookies/CSRF, tenant isolation/default deny, no professional authority, accounting conservation, throttling.');
}finally{server.close();delete process.env.EVE_PUBLIC_PREVIEW_HOSTS;process.chdir(original);fs.rmSync(temp,{recursive:true,force:true});}
