import assert from 'node:assert/strict';
import fs from 'node:fs'; import path from 'node:path';
import { AnyDocParser } from '../..//src/lib/parser/anydocParser.js';
import { extractBankStatementFromDocument } from '../bankStatementExtractor.js';
import { assessBankStatementCompleteness } from '../cpaOrganization/bankStatementCompletenessAdapter.js';
import { BANK_ENGAGEMENT_ID,BANK_WORKSPACE_ID,bankEvidenceDir,fixtureManifestPath,loadBankStatementPdf,sha256,type BankFixtureVariant } from './fixtures/bankStatementCompletenessFixture.js';
const parser=new AnyDocParser();
async function run(variant:BankFixtureVariant){ const bytes=loadBankStatementPdf(variant); const sourceSha=sha256(bytes); const doc=await parser.parse({filename:`bank-${variant}.pdf`,originalName:`bank-${variant}.pdf`,mimeType:'application/pdf',buffer:bytes}); doc.source.hash=sourceSha; const documentId=`doc-bank-${variant}`; const extraction=extractBankStatementFromDocument({doc,workspaceId:BANK_WORKSPACE_ID,documentId,filename:`bank-${variant}.pdf`}); assert.equal(extraction.success,true); const assessment=assessBankStatementCompleteness({doc,extraction,workspaceId:BANK_WORKSPACE_ID,engagementId:BANK_ENGAGEMENT_ID,documentId,filename:`bank-${variant}.pdf`}); return {bytes,sourceSha,doc,extraction,assessment}; }
const complete=await run('complete');
assert.equal(complete.doc.page_count,4); assert.equal(complete.extraction.transactions.length,4); assert.equal(complete.extraction.transactions[0].amount,500,'date fragment must never become transaction amount'); assert.equal((complete.extraction.transactions[0] as any).sourcePage,2); assert.equal((complete.extraction.transactions[2] as any).sourcePage,3); assert.equal((complete.extraction.summary as any).currency,'USD'); assert.equal((complete.extraction.summary as any).beginningBalance,1000); assert.equal((complete.extraction.summary as any).endingBalance,1150); assert.equal((complete.extraction.summary as any).calculatedEndingBalance,1150); assert.equal((complete.extraction.summary as any).reconciliationPassed,true); assert.deepEqual(complete.assessment.missingLogicalPages,[]); assert.equal(complete.assessment.summary.reconciliationStatus,'PASS'); assert.equal(new Set(complete.extraction.facts.map(f=>f.id)).size,complete.extraction.facts.length,'bank balance fact IDs must be unique');
const nonmaterial=await run('missing-disclosure'); assert.deepEqual(nonmaterial.assessment.observedLogicalPages,[1,2,3]); assert.deepEqual(nonmaterial.assessment.missingLogicalPages,[4]); assert.equal(nonmaterial.assessment.gaps[0].gapType,'MISSING_PAGE'); assert.equal(nonmaterial.assessment.gaps[0].explicitMateriality,'NON_MATERIAL'); assert.equal(nonmaterial.assessment.endingBalanceDecision.sourceCompletenessState,'SOURCE_GAP_NON_MATERIAL_FOR_CURRENT_PURPOSE'); assert.equal(nonmaterial.assessment.endingBalanceDecision.taskEvidenceSufficiencyState,'SUFFICIENT_FOR_CURRENT_PURPOSE'); assert.equal(nonmaterial.assessment.transactionPopulationDecision.taskEvidenceSufficiencyState,'SUFFICIENT_FOR_CURRENT_PURPOSE');
const material=await run('missing-transactions'); assert.deepEqual(material.assessment.observedLogicalPages,[1,3,4]); assert.deepEqual(material.assessment.missingLogicalPages,[2]); assert.equal(material.assessment.gaps[0].gapType,'MISSING_TRANSACTION_RANGE'); assert.equal(material.assessment.gaps[0].explicitMateriality,'MATERIAL'); assert.equal(material.assessment.summary.beginningBalance,1000); assert.equal(material.assessment.summary.endingBalance,1150); assert.equal(material.assessment.summary.totalDeposits,50); assert.equal(material.assessment.summary.totalWithdrawals,100); assert.equal(material.assessment.summary.calculatedEndingBalance,950); assert.equal(material.assessment.summary.variance,-200); assert.equal(material.assessment.summary.reconciliationStatus,'FAIL'); assert.deepEqual(material.assessment.endingBalanceDecision.allowedConclusionIds,['ending-cash']); assert.deepEqual(material.assessment.transactionPopulationDecision.blockedConclusionIds,['complete-transaction-population']); assert.equal(material.assessment.transactionPopulationDecision.recommendedAction,'REQUEST_ADDITIONAL_EVIDENCE'); assert.equal(material.assessment.clarificationRecommended,true);
const unknown=await run('missing-unknown'); assert.deepEqual(unknown.assessment.missingLogicalPages,[2]); assert.equal(unknown.assessment.gaps[0].explicitMateriality,'UNKNOWN'); assert.equal(unknown.assessment.summary.reconciliationStatus,'PASS'); assert.deepEqual(unknown.assessment.endingBalanceDecision.reviewRequiredConclusionIds,['ending-cash']); assert.deepEqual(unknown.assessment.transactionPopulationDecision.blockedConclusionIds,['complete-transaction-population'],'a complete-population conclusion must fail closed when an unknown missing page may contain population members'); assert.equal(unknown.assessment.endingBalanceDecision.recommendedAction,'REVIEW_MATERIALITY'); assert.equal(unknown.assessment.transactionPopulationDecision.recommendedAction,'REQUEST_ADDITIONAL_EVIDENCE');
// Currency must not be invented and absent balances must not become zero.
const noCurrencyDoc:any={...complete.doc,metadata:{...complete.doc.metadata,currency:undefined},pages:complete.doc.pages!.map(p=>({...p,text:p.text.replace(/CURRENCY USD/g,'')})),markdown:(complete.doc.markdown||'').replace(/CURRENCY USD/g,''),raw_text:(complete.doc.raw_text||'').replace(/CURRENCY USD/g,''),sections:(complete.doc.sections||[]).map(s=>({...s,text:s.text.replace(/CURRENCY USD/g,'')}))};
const noCurrency=extractBankStatementFromDocument({doc:noCurrencyDoc,workspaceId:'ws',documentId:'doc-no-currency',filename:'bank-no-currency.pdf'}); assert.equal((noCurrency.summary as any).currency,undefined,'dollar symbol alone must not silently establish USD');
const noBalancesDoc:any={document_id:'doc-no-bal',source:{filename:'no-bal.txt',format:'txt'},metadata:{},raw_text:'09/02/2026 TEST DEPOSIT 25.00',markdown:'09/02/2026 TEST DEPOSIT 25.00',pages:[{page_number:1,text:'09/02/2026 TEST DEPOSIT 25.00'}],sections:[]};
const noBalances=extractBankStatementFromDocument({doc:noBalancesDoc,workspaceId:'ws',documentId:'doc-no-bal',filename:'no-bal.txt'}); assert.equal(noBalances.success,true); assert.equal((noBalances.summary as any).beginningBalance,undefined); assert.equal((noBalances.summary as any).endingBalance,undefined); assert.equal((noBalances.summary as any).calculatedEndingBalance,undefined); assert.equal((noBalances.summary as any).reconciliationPassed,false);
const fixtureManifest=JSON.parse(fs.readFileSync(fixtureManifestPath(),'utf8'));
const proof={marker:'P2_BANK_STATEMENT_SOURCE_SUFFICIENCY_CASES=PASS',fixtureManifest,cases:{complete:{sha:complete.sourceSha,reconciliation:complete.assessment.summary.reconciliationStatus},nonmaterial:{sha:nonmaterial.sourceSha,missing:nonmaterial.assessment.missingLogicalPages,ending:nonmaterial.assessment.endingBalanceDecision.taskEvidenceSufficiencyState,transactions:nonmaterial.assessment.transactionPopulationDecision.taskEvidenceSufficiencyState},material:{sha:material.sourceSha,missing:material.assessment.missingLogicalPages,reconciliation:material.assessment.summary.reconciliationStatus,variance:material.assessment.summary.variance,ending:material.assessment.endingBalanceDecision.allowedConclusionIds,blocked:material.assessment.transactionPopulationDecision.blockedConclusionIds},unknown:{sha:unknown.sourceSha,missing:unknown.assessment.missingLogicalPages,ending:unknown.assessment.endingBalanceDecision.reviewRequiredConclusionIds,transactionsBlocked:unknown.assessment.transactionPopulationDecision.blockedConclusionIds}}}; fs.writeFileSync(path.join(bankEvidenceDir(),'source-sufficiency-cases.json'),JSON.stringify(proof,null,2)); console.log('P2_BANK_STATEMENT_SOURCE_SUFFICIENCY_CASES=PASS');
