import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import * as XLSXModule from 'xlsx';
const XLSX:any=(XLSXModule as any).default||XLSXModule;
import { buildInvoiceApFact, buildInvoiceApInterpretation, INVOICE_DOCUMENT_ID, INVOICE_ENGAGEMENT_ID, INVOICE_FACT_ID, INVOICE_SHA256, INVOICE_WORKSPACE_ID, invoiceEvidenceDir } from './fixtures/invoiceApFiveDimensionFixture.js';

const evidenceDir=invoiceEvidenceDir(); const reportsDir=path.join(evidenceDir,'reports'); fs.mkdirSync(reportsDir,{recursive:true}); process.env.HERMES_REPORTS_DIR=reportsDir;
const {deliverableArtifactService}=await import('../cpaOrganization/deliverableArtifactService.js');
const invoice=buildInvoiceApInterpretation(); const fact=buildInvoiceApFact(invoice);
const report=await deliverableArtifactService.compileAndRegisterDeliverable({reportId:'REP-INVOICE-AP-260916-1042',engagementId:INVOICE_ENGAGEMENT_ID,workspaceId:INVOICE_WORKSPACE_ID,version:'v1.0',title:'Invoice AP Evidence Review Draft',clientName:'Eve Academy AP Test Client',period:'2026-09-16',currency:'USD',status:'AI_PREPARED',apReview:invoice,facts:[{
 id:fact.id,canonicalMetric:fact.canonicalMetric,label:fact.labelNormalized,value:fact.normalizedValue,statement:'AP_EVIDENCE',sourceDoc:'invoice.png',page:1,verificationStatus:'VERIFIED',evidenceStatus:'CONFIRMED',documentId:INVOICE_DOCUMENT_ID,reportingPeriod:'2026-09-16',sourceText:fact.sourceText,sourceBlockIds:['SB-INVOICE-TOTAL'],sourceSha256:fact.sourceSha256,sourceArtifactId:fact.sourceArtifactId,sourceProvenanceId:fact.sourceProvenanceId,sourceProvenanceIds:fact.sourceProvenanceIds,sourceCoordinate:fact.sourceCoordinate,sourceCoordinates:fact.sourceCoordinates,sourceExtractionMethod:fact.sourceExtractionMethod,sourceExtractionVersion:fact.sourceExtractionVersion,
}]});
assert.equal(report.status,'AI_PREPARED'); assert.ok(report.formats.pdf&&report.formats.json&&report.formats.xlsx&&report.formats.csvLeadSchedules);
const pdfBytes=fs.readFileSync(report.formats.pdf!.filepath); assert.equal(pdfBytes.subarray(0,5).toString(),'%PDF-'); const pdfSha=crypto.createHash('sha256').update(pdfBytes).digest('hex'); assert.equal(pdfSha,report.formats.pdf!.sha256);
const {PDFParse}=await import('pdf-parse'); const parser=new PDFParse({data:pdfBytes}); let pdfText=''; try{pdfText=(await parser.getText()).text;}finally{await parser.destroy();}
for(const expected of ['Invoice AP Evidence Review Draft','Accounts payable invoice review','SYNTHETIC OFFICE SUPPLY CO.','INV-260916-1042','10/16/2026','PO-EVE-1001','Total due: 187.25','Reconciliation: PASS','Semantic adjudication: RESOLVED_FIELD_CONSENSUS','INV0ICE INV-260916-1042','INVOICE INV-260916-1042','Three-way match: NOT_TESTABLE','Approval: REVIEW_REQUIRED','Payment eligibility: BLOCKED','Payment status: UNKNOWN','Posting: NOT_POSTED',INVOICE_SHA256,'TOTAL DUE $187.25']) assert.ok(pdfText.includes(expected),`PDF missing ${expected}`);
const json=JSON.parse(fs.readFileSync(report.formats.json!.filepath,'utf8')); assert.equal(json.apReview.invoiceNumber.value,'INV-260916-1042'); assert.equal(json.apReview.apControl.paymentEligibility,'BLOCKED'); assert.equal(json.apReview.apControl.threeWayMatchStatus,'NOT_TESTABLE'); assert.equal(json.facts[0].sourceSha256,INVOICE_SHA256);
const csv=fs.readFileSync(report.formats.csvLeadSchedules!.filepath,'utf8'); for(const expected of ['AP INVOICE REVIEW','INV-260916-1042','REVIEW_REQUIRED','BLOCKED','NOT_TESTABLE',INVOICE_SHA256,'TOTAL DUE $187.25']) assert.ok(csv.includes(expected),`CSV missing ${expected}`);
const workbook=XLSX.readFile(report.formats.xlsx!.filepath); assert.ok(workbook.Sheets['AP Review']); const apRows:any[][]=XLSX.utils.sheet_to_json(workbook.Sheets['AP Review'],{header:1,raw:false}); const apText=apRows.flat().map(v=>String(v??'')).join(' | '); for(const expected of ['INV-260916-1042','PO-EVE-1001','RESOLVED_FIELD_CONSENSUS','NOT_TESTABLE','REVIEW_REQUIRED','BLOCKED','NOT_POSTED',INVOICE_SHA256]) assert.ok(apText.includes(expected),`XLSX AP Review missing ${expected}`);
const leadRows:any[][]=XLSX.utils.sheet_to_json(workbook.Sheets['Lead Schedules'],{header:1,raw:false}); const leadText=leadRows.flat().map(v=>String(v??'')).join(' | '); for(const expected of [INVOICE_SHA256,'TOTAL DUE $187.25']) assert.ok(leadText.includes(expected));
const proof={marker:'P2_INVOICE_AP_DELIVERABLE_TRUTH=PASS',sourceSha256:INVOICE_SHA256,factId:INVOICE_FACT_ID,invoiceNumber:invoice.invoiceNumber.value,reportId:report.reportId,version:report.version,pdfSha256:pdfSha,pdfBytes:pdfBytes.length,formats:{pdf:report.formats.pdf!.sha256,json:report.formats.json!.sha256,xlsx:report.formats.xlsx!.sha256,csv:report.formats.csvLeadSchedules!.sha256}}; fs.writeFileSync(path.join(evidenceDir,'deliverable-truth.json'),JSON.stringify(proof,null,2)); console.log('P2_INVOICE_AP_DELIVERABLE_TRUTH=PASS');
