import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { AnyDocParser } from '../../src/lib/parser/anydocParser.js';
import { OCRParser } from '../../src/lib/parser/ocrParser.js';
import { LocalOcrClient } from '../../src/lib/ocr/localOcrClient.js';
import { applySelectivePdfOcr, getPdfPagesRequiringOcr, shouldUseSelectivePdfOcr } from '../../src/lib/parser/pdfOcrFallback.js';

const dir=process.env.MIXED_PDF_OCR_ACCEPTANCE_DIR||'/tmp/eve-mixed-pdf-ocr';
const fixture=JSON.parse(fs.readFileSync(path.join(dir,'fixture-manifest.json'),'utf8'));
const buffer=fs.readFileSync(path.join(dir,fixture.filename));
const sha=crypto.createHash('sha256').update(buffer).digest('hex');
assert.equal(sha,fixture.sha256);
const inspection={detectedType:'pdf',mimeType:'application/pdf'};
const fileInput={filename:fixture.filename,originalName:fixture.filename,mimeType:'application/pdf',size:buffer.length,buffer};
const native:any=await new AnyDocParser().parse(fileInput,inspection as any);
assert.deepEqual(native.pageManifests.map((p:any)=>[p.page_number,p.native_text_available]),[[1,true],[2,false],[3,true]]);
assert.deepEqual(getPdfPagesRequiringOcr(native,inspection),[2]);
assert.equal(shouldUseSelectivePdfOcr(native,inspection),true);

const calls:any[]=[];
const fakeFetch:any=async (_url:string,init:any)=>{const body=JSON.parse(init.body);calls.push(body);const rotation=Number(body.rotationDegrees||0);const good=rotation===270;const confidence=good?0.99:0.40;return new Response(JSON.stringify({engine:'paddleocr',engineVersion:'3.7.0',serviceVersion:'test',model:'fake-selective-pdf',sourceSha256:body.sourceSha256,elapsedMs:1,appliedRotationDegrees:rotation,coordinateSpace:'ORIGINAL_SOURCE',pages:[{pageNumber:body.pdfPageNumbers[0],width:1200,height:900,regions:[{regionId:`p${body.pdfPageNumbers[0]}-r1`,text:good?'SCANNED PAGE TWO TOTAL USD 53.23':'SCANNED PAGE TWO TOTAL USD 53.23',confidence,boundingBox:{x:0.15,y:0.20,width:0.60,height:0.08,unit:'NORMALIZED'}}]}],warnings:[]}),{status:200,headers:{'content-type':'application/json'}});};
const client=new LocalOcrClient({primaryUrl:'http://paddle.test',fallbackUrl:'',fetchImpl:fakeFetch,orientationRetryEnabled:true,orientationRetryAngles:[90,270,180],primaryAverageConfidenceFloor:0.90,materialConfidenceFloor:0.85});
const selective=await applySelectivePdfOcr({nativeDoc:native,fileInput,inspection,ocrParser:new OCRParser(client)});
const doc:any=selective.document;
assert.deepEqual(selective.ocrPageNumbers,[2]);
assert.ok(calls.length>=4,'expected initial OCR plus bounded orientation retries');
assert.ok(calls.every(c=>JSON.stringify(c.pdfPageNumbers)==='[2]'),'native pages must never be sent to OCR');
assert.equal(doc.parser.engine,'anydoc+selective-local-ocr');
assert.deepEqual(doc.parser.selectiveOcrPages,[2]);
assert.equal(doc.pageManifests[0].evidence_mode,'NATIVE_TEXT');
assert.equal(doc.pageManifests[1].evidence_mode,'OCR');
assert.equal(doc.pageManifests[1].ocr_rotation_degrees,270);
assert.equal(doc.pageManifests[2].evidence_mode,'NATIVE_TEXT');
assert.match(doc.pages[0].text,/ALPHA-NATIVE-P1/);assert.match(doc.pages[1].text,/TOTAL USD 53\.23/);assert.match(doc.pages[2].text,/OMEGA-NATIVE-P3/);
assert.match(doc.raw_text,/ALPHA-NATIVE-P1/);assert.match(doc.raw_text,/TOTAL USD 53\.23/);assert.match(doc.raw_text,/OMEGA-NATIVE-P3/);
const coords=(doc.sourceValueProvenance||[]).flatMap((p:any)=>p.coordinates||[]);
const nativeCoords=coords.filter((c:any)=>c.evidenceMode==='NATIVE_TEXT');const ocrCoords=coords.filter((c:any)=>c.evidenceMode==='OCR');
assert.deepEqual(nativeCoords.map((c:any)=>c.pageNumber).sort(),[1,3]);assert.ok(ocrCoords.length>=1);assert.ok(ocrCoords.every((c:any)=>c.pageNumber===2));assert.ok(coords.every((c:any)=>c.sourceSha256===sha));assert.ok(coords.every((c:any)=>c.sourceArtifactId===`artifact-pdf-${sha.slice(0,24)}`));
const proof={marker:'P2_MIXED_PDF_SELECTIVE_OCR_SOURCE_TRUTH=PASS',sourceSha256:sha,nativePages:[1,3],ocrPages:[2],selectedRotationDegrees:doc.pageManifests[1].ocr_rotation_degrees,ocrRequestPageSelections:calls.map(c=>c.pdfPageNumbers),pageModes:doc.pageManifests.map((p:any)=>({pageNumber:p.page_number,mode:p.evidence_mode,ocrUsed:p.ocr_used,rotation:p.ocr_rotation_degrees||0})),coordinateCount:coords.length};
fs.writeFileSync(path.join(dir,'source-truth.json'),JSON.stringify(proof,null,2));
console.log('P2_MIXED_PDF_SELECTIVE_OCR_SOURCE_TRUTH=PASS');
