import assert from 'node:assert/strict';
import fs from 'node:fs'; import path from 'node:path'; import puppeteer from 'puppeteer-core';
import { RECEIPT_PROVENANCE_ID,RECEIPT_SHA256 } from './fixtures/receiptFiveDimensionFixture.js';
import { buildSourceDashboardEngagement,loadSourceDashboardManifest,SOURCE_DASHBOARD_ENGAGEMENT_ID,SOURCE_DASHBOARD_RECEIPT_FACT_ID,SOURCE_DASHBOARD_SPREADSHEET_FACT_ID,SOURCE_DASHBOARD_TAMPERED_FACT_ID,sourceDashboardDir } from './fixtures/sourceToDashboardFixture.js';
const baseUrl=process.env.EVE_TEST_BASE_URL||'http://127.0.0.1:4173';const dir=sourceDashboardDir();const manifest=loadSourceDashboardManifest();const engagement=buildSourceDashboardEngagement(true);const candidates=[process.env.CHROME_BIN,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean) as string[];const executablePath=candidates.find(p=>fs.existsSync(p));if(!executablePath)throw new Error('MISSING_BROWSER_EXECUTABLE');const browser=await puppeteer.launch({executablePath,headless:true,args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']});
try {const page=await browser.newPage();await page.setViewport({width:1440,height:1050});await page.setRequestInterception(true);page.on('request',async request=>{try{const url=new URL(request.url());if(url.origin!==new URL(baseUrl).origin||!url.pathname.startsWith('/api/'))return request.continue();let payload:any={};if(url.pathname==='/api/cpa/engagements/universal')payload={engagements:[{engagementId:engagement.engagementId,workspaceId:engagement.workspaceId,classification:'ACADEMY',isCustomer:false,clientName:engagement.clientName,period:engagement.period,framework:engagement.framework,functionalCurrency:'USD',currentStage:'EVIDENCE_REVIEW',openReviewNotesCount:0,documentsCount:2,canonicalFactsCount:3}]};else if(url.pathname===`/api/cpa/engagements/${encodeURIComponent(SOURCE_DASHBOARD_ENGAGEMENT_ID)}`||url.pathname===`/api/cpa/engagements/${SOURCE_DASHBOARD_ENGAGEMENT_ID}`)payload={engagement};else if(url.pathname==='/api/cpa/reports/library')payload={reports:[]};else if(url.pathname==='/api/queue/jobs')payload={jobs:[]};else if(url.pathname==='/api/health')payload={status:'ok'};await request.respond({status:200,contentType:'application/json',body:JSON.stringify(payload)});}catch{request.abort();}});
const response=await page.goto(`${baseUrl}/?view=financials-income`,{waitUntil:'networkidle0',timeout:30000});assert.ok(response?.ok());
async function cell(id:string){const sel=`[data-eve-financial-value="true"][data-canonical-fact-id="${id}"]`;await page.waitForSelector(sel,{visible:true,timeout:15000});return {sel,data:await page.$eval(sel,(el:any)=>({text:el.innerText.trim(),factId:el.dataset.canonicalFactId,renderId:el.dataset.renderId,status:el.dataset.provenanceStatus,metric:el.dataset.canonicalMetric}))};}
const spreadsheetCell=await cell(SOURCE_DASHBOARD_SPREADSHEET_FACT_ID),receiptCell=await cell(SOURCE_DASHBOARD_RECEIPT_FACT_ID),tamperedCell=await cell(SOURCE_DASHBOARD_TAMPERED_FACT_ID);for(const c of [spreadsheetCell,receiptCell,tamperedCell])assert.equal(c.data.text,'$53.23');assert.equal(spreadsheetCell.data.status,'verified');assert.equal(receiptCell.data.status,'verified');assert.equal(tamperedCell.data.status,'review_required');assert.ok(spreadsheetCell.data.renderId&&receiptCell.data.renderId&&tamperedCell.data.renderId);
await page.click(spreadsheetCell.sel);await page.waitForSelector('[role="dialog"]',{visible:true,timeout:10000});let text=await page.$eval('[role="dialog"]',el=>(el as HTMLElement).innerText);for(const expected of ['Source-to-Pixel Provenance','revenue-register.xlsx','Revenue Register!B2',manifest.spreadsheet.provenanceId,'Revenue | 53.23 | USD'])assert.ok(text.includes(expected),`spreadsheet drawer missing ${expected}`);await page.click('[data-eve-action-id="evidence.technical"]');text=await page.$eval('[role="dialog"]',el=>(el as HTMLElement).innerText);for(const expected of [manifest.spreadsheet.sha256,SOURCE_DASHBOARD_SPREADSHEET_FACT_ID,spreadsheetCell.data.renderId])assert.ok(text.includes(expected),`spreadsheet technical trace missing ${expected}`);await page.click('[data-eve-action-id="evidence.close"]');await page.waitForSelector('[role="dialog"]',{hidden:true});
await page.click(receiptCell.sel);await page.waitForSelector('[role="dialog"]',{visible:true,timeout:10000});await page.click('[data-eve-action-id="evidence.summary"]');text=await page.$eval('[role="dialog"]',el=>(el as HTMLElement).innerText);for(const expected of ['Source-to-Pixel Provenance','receipt.png','TOTAL $53.23','900×1000','fixture-total-glyph-region',RECEIPT_PROVENANCE_ID])assert.ok(text.includes(expected),`receipt drawer missing ${expected}`);await page.click('[data-eve-action-id="evidence.technical"]');text=await page.$eval('[role="dialog"]',el=>(el as HTMLElement).innerText);for(const expected of [RECEIPT_SHA256,SOURCE_DASHBOARD_RECEIPT_FACT_ID,receiptCell.data.renderId])assert.ok(text.includes(expected),`receipt technical trace missing ${expected}`);await page.click('[data-eve-action-id="evidence.close"]');
const screenshot=path.join(dir,'source-to-dashboard-product-truth.png');await page.screenshot({path:screenshot,fullPage:true});const proof={marker:'P2_SOURCE_TO_DASHBOARD_PRODUCT_TRUTH_BROWSER=PASS',visibleValue:'$53.23',spreadsheet:{factId:SOURCE_DASHBOARD_SPREADSHEET_FACT_ID,renderId:spreadsheetCell.data.renderId,status:spreadsheetCell.data.status,sourceSha256:manifest.spreadsheet.sha256,sourceLocator:'Revenue Register!B2',provenanceId:manifest.spreadsheet.provenanceId},receipt:{factId:SOURCE_DASHBOARD_RECEIPT_FACT_ID,renderId:receiptCell.data.renderId,status:receiptCell.data.status,sourceSha256:RECEIPT_SHA256,sourceLocator:'fixture-total-glyph-region',provenanceId:RECEIPT_PROVENANCE_ID},tampered:{factId:SOURCE_DASHBOARD_TAMPERED_FACT_ID,renderId:tamperedCell.data.renderId,status:tamperedCell.data.status},screenshot,browserVersion:await browser.version()};fs.writeFileSync(path.join(dir,'product-truth.json'),JSON.stringify(proof,null,2));console.log('P2_SOURCE_TO_DASHBOARD_PRODUCT_TRUTH_BROWSER=PASS');} finally {await browser.close();}
